import { useEffect,useState } from 'react'
import { useNavigate,useSearchParams,Link } from 'react-router-dom'
import { api,ApiError } from '../lib/api'

export default function AccountAction(){
  const [params]=useSearchParams(),navigate=useNavigate(),token=params.get('token')??'',purpose=params.get('purpose')
  const [state,setState]=useState<'checking'|'valid'|'done'|'error'>('checking'),[error,setError]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false)
  useEffect(()=>{if(!token||!['magic_login','password_reset'].includes(purpose??'')){setState('error');setError('Invalid link');return}void api(`/api/auth/action-token/inspect?purpose=${purpose}&token=${encodeURIComponent(token)}`).then(()=>{if(purpose==='magic_login')return api('/api/auth/magic-login',{method:'POST',body:JSON.stringify({token})}).then(()=>navigate('/',{replace:true}));setState('valid')}).catch((e)=>{setState('error');setError(e instanceof ApiError?e.code:'Invalid or expired link')})},[token,purpose,navigate])
  const reset=async(e:React.FormEvent)=>{e.preventDefault();if(password.length<8){setError('Password must be at least 8 characters');return}if(password!==confirm){setError('Passwords do not match');return}setBusy(true);setError('');try{await api('/api/auth/password-reset',{method:'POST',body:JSON.stringify({token,password})});setState('done')}catch(e){setError(e instanceof ApiError?e.code:'Reset failed')}finally{setBusy(false)}}
  return <main className="account-action-page"><section className="auth-card"><div className="auth-brand"><strong>OnTarget</strong><span>Secure account access</span></div>{state==='checking'&&<p>Checking your secure link…</p>}{state==='error'&&<><div className="login-error">{error}</div><Link className="btn-primary" to="/login">Return to sign in</Link></>}{state==='valid'&&purpose==='password_reset'&&<form onSubmit={reset}><h2>Set a new password</h2><label className="login-label">New password</label><input autoFocus className="login-input" type="password" minLength={8} value={password} onChange={(e)=>setPassword(e.target.value)}/><label className="login-label">Confirm password</label><input className="login-input" type="password" minLength={8} value={confirm} onChange={(e)=>setConfirm(e.target.value)}/>{error&&<div className="login-error">{error}</div>}<button className="login-btn" disabled={busy}>{busy?'Saving…':'Reset password'}</button></form>}{state==='done'&&<><h2>Password updated</h2><p>All previous sessions were revoked.</p><Link className="btn-primary" to="/login">Sign in</Link></>}</section></main>
}
