import { useCallback, useEffect, useState } from 'react'
import PanelShell from '../components/PanelShell'
import { useAuth } from '../auth/AuthContext'
import { api, ApiError } from '../lib/api'
import { useLocale } from '../lib/locale'

interface Config { p2p_enabled: boolean; p2p_asset: string; p2p_fiat: string; max_p2p_order_amount: number | null; max_p2p_24h_amount: number | null; has_credentials: boolean; updated_at: string | null }
interface Data { config: Config | null; execution_capability: 'unavailable'; execution_reason: string }

export default function Binance() {
  const { t } = useLocale(); const { user } = useAuth(); const isSuperAdmin = user?.role === 'super_admin'
  const [data, setData] = useState<Data | null>(null); const [err, setErr] = useState(''); const [msg, setMsg] = useState('')
  const [limits, setLimits] = useState({ perOrder: '', daily: '' }); const [keys, setKeys] = useState({ api_key: '', api_secret: '' })
  const load = useCallback(async () => { try { const d = await api<Data>('/api/binance'); setData(d); setLimits({ perOrder: d.config?.max_p2p_order_amount ? String(d.config.max_p2p_order_amount) : '', daily: d.config?.max_p2p_24h_amount ? String(d.config.max_p2p_24h_amount) : '' }); setErr('') } catch (e) { setErr(e instanceof ApiError && e.code === 'migration_required' ? t('يلزم تطبيق ترحيل قاعدة بيانات Binance أولاً.', 'The Binance database migration must be applied first.') : t('تعذر تحميل إعداد Binance.', 'Unable to load Binance configuration.')) } }, [t])
  useEffect(() => { void load() }, [load])
  const saveLimits = async (enabled?: boolean) => { setErr(''); setMsg(''); try { if (!limits.perOrder || !limits.daily) throw new Error('limits'); await api('/api/binance/config', { method: 'PUT', body: JSON.stringify({ max_p2p_order_amount: Number(limits.perOrder), max_p2p_24h_amount: Number(limits.daily), ...(enabled === undefined ? {} : { p2p_enabled: enabled }) }) }); setMsg(t('تم حفظ الحدود.', 'Limits saved.')); await load() } catch (e) { setErr(e instanceof ApiError && e.code === 'super_admin_required' ? t('هذه العملية متاحة لـ super_admin فقط.', 'Only super_admin can perform this action.') : t('أدخل حدَّين موجبين، ولا يمكن التفعيل قبل حفظ المفتاح.', 'Enter two positive limits; credentials are required before enabling.')) } }
  const saveKeys = async () => { setErr(''); setMsg(''); try { await api('/api/binance/credentials', { method: 'PUT', body: JSON.stringify(keys) }); setKeys({ api_key: '', api_secret: '' }); setMsg(t('حُفظ المفتاح داخل Supabase Vault وأُبقي التكامل موقوفاً.', 'Credentials saved in Supabase Vault; the integration remains disabled.')); await load() } catch { setErr(t('تعذر حفظ المفتاح بأمان.', 'Unable to store credentials securely.')) } }
  const cfg = data?.config
  return <PanelShell>
    <section className="page-head"><h2>Binance P2P — {t('تنفيذ يدوي', 'Manual execution')}</h2><p className="page-sub">{t('لا triggers ولا cron ولا تنفيذ تلقائي. كل عملية مستقبلية تتطلب تأكيداً بشرياً مسجلاً.', 'No triggers, cron, or automatic execution. Every future order requires a recorded human confirmation.')}</p></section>
    <div className="card warn"><strong>{t('قيد أمان فعّال:', 'Active safety lock:')}</strong> {t('Binance لا توثّق حالياً API عامة لإنشاء أوامر P2P أو قراءة عروض السوق. لذلك التنفيذ والعروض مقفولان، ولن يستخدم النظام واجهات الموقع غير الموثقة.', 'Binance currently documents no public API for placing P2P orders or reading marketplace ads. Execution and offers are therefore locked; undocumented website endpoints are not used.')}</div>
    <div className="card"><strong>{t('قبل إدخال المفتاح:', 'Before entering credentials:')}</strong> {t('أنشئ مفتاحاً بصلاحية P2P فقط، وعطّل Withdrawal تماماً من إعدادات Binance.', 'Create a P2P-only key and disable Withdrawal completely in Binance settings.')}</div>
    {err && <div className="card warn">{err}</div>}{msg && <div className="card">{msg}</div>}
    {data && <section className="card recent-card"><div className="recent-head"><h3>{t('الحالة والحدود', 'Status and limits')}</h3><span className={`pay-status-badge ${cfg?.p2p_enabled ? 'st-paid' : 'st-dim'}`}>{cfg?.p2p_enabled ? t('مفعّل', 'Enabled') : t('موقوف', 'Disabled')}</span></div>
      <div className="binance-grid"><label className="filter-field" style={{ flexDirection: 'column', alignItems: 'stretch' }}>{t('الحد الأقصى للعملية (EGP)', 'Maximum per order (EGP)')}<input className="login-input" type="number" min="0.01" step="0.01" value={limits.perOrder} disabled={!isSuperAdmin} onChange={e => setLimits({ ...limits, perOrder: e.target.value })} /></label><label className="filter-field" style={{ flexDirection: 'column', alignItems: 'stretch' }}>{t('الحد المتحرك خلال 24 ساعة (EGP)', 'Rolling 24-hour maximum (EGP)')}<input className="login-input" type="number" min="0.01" step="0.01" value={limits.daily} disabled={!isSuperAdmin} onChange={e => setLimits({ ...limits, daily: e.target.value })} /></label></div>
      {isSuperAdmin && <div className="control-row" style={{ marginTop: 12 }}><button className="btn-primary btn-sm" onClick={() => void saveLimits()}>{t('حفظ الحدود', 'Save limits')}</button>{cfg?.p2p_enabled ? <button className="btn-ghost btn-sm" onClick={() => void saveLimits(false)}>{t('إيقاف', 'Disable')}</button> : <button className="btn-ghost btn-sm" onClick={() => void saveLimits(true)}>{t('تفعيل يدوي', 'Enable manual mode')}</button>}</div>}
    </section>}
    {isSuperAdmin && <section className="card recent-card"><h3>{t('مفتاح API — إدخال مرة واحدة', 'API credentials — one-time entry')}</h3><p className="page-sub">{cfg?.has_credentials ? t('يوجد مفتاح محفوظ. لن يُعرض مطلقاً؛ الحفظ هنا يستبدله ويوقف التكامل.', 'Credentials exist. They are never displayed; saving here replaces them and disables the integration.') : t('لا يوجد مفتاح محفوظ.', 'No credentials stored.')}</p><div className="binance-grid"><input className="login-input" type="password" autoComplete="off" placeholder="API Key" value={keys.api_key} onChange={e => setKeys({ ...keys, api_key: e.target.value })} /><input className="login-input" type="password" autoComplete="new-password" placeholder="API Secret" value={keys.api_secret} onChange={e => setKeys({ ...keys, api_secret: e.target.value })} /></div><button className="btn-primary btn-sm" style={{ marginTop: 12 }} disabled={!keys.api_key || !keys.api_secret} onClick={() => void saveKeys()}>{t('حفظ آمن في Vault', 'Store securely in Vault')}</button></section>}
    <section className="card recent-card"><h3>{t('عروض P2P', 'P2P offers')}</h3><p className="sidebar-hint">{t('غير متاحة عبر API Binance الرسمية. لا يوجد زر تنفيذ حتى توفير واجهة موثقة ومخوّلة للحساب.', 'Unavailable through Binance’s official API. No execute button is exposed until a documented, account-authorized endpoint is available.')}</p></section>
  </PanelShell>
}
