import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react'
import { Download, RefreshCw } from 'lucide-react'
import PanelShell from '../components/PanelShell'
import { api, ApiError } from '../lib/api'
import { money } from '../lib/deposits'
import { useAuth } from '../auth/AuthContext'
import { useLocale } from '../lib/locale'

interface Settlement { id: string; settlement_at: string; direction: 'in' | 'out'; recipient_name: string; amount: number; method: string; wallet: string | null; sms_id: number | null; note: string | null; created_by: string | null }
interface Data { rows: Settlement[]; totals: { total_in: number; total_out: number; net: number } }

export default function CashSettlements() {
  const { t } = useLocale(); const { can } = useAuth(); const [data, setData] = useState<Data | null>(null); const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const [busy, setBusy] = useState(false); const [err, setErr] = useState<string | null>(null)
  const [form, setForm] = useState({ direction: 'out', recipient_name: '', amount: '', method: 'Cash', wallet: '', sms_id: '', note: '' })
  const load = useCallback(async () => { setBusy(true); try { const q = new URLSearchParams(); if (from) q.set('from', from); if (to) q.set('to', to); setData(await api<Data>(`/api/cash-settlements?${q}`)); setErr(null) } catch (e) { setErr(e instanceof ApiError && e.status === 403 ? t('لا تملك صلاحية عرض التسويات.', 'You lack permission to view settlements.') : t('تعذّر تحميل التسويات.', 'Failed to load settlements.')) } finally { setBusy(false) } }, [from, to, t])
  useEffect(() => { void load() }, [load])
  const add = async (event: FormEvent) => { event.preventDefault(); setBusy(true); try { await api('/api/cash-settlements', { method: 'POST', body: JSON.stringify(form) }); setForm({ ...form, recipient_name: '', amount: '', sms_id: '', note: '' }); await load() } catch (e) { setErr(e instanceof ApiError ? e.message : t('تعذّر حفظ حركة الكاش.', 'Could not save cash movement.')) } finally { setBusy(false) } }
  const exportCsv = () => { if (!data) return; const esc = (v: unknown) => `"${String(v ?? '').replaceAll('"', '""')}"`; const csv = [['Date','Direction','Name','Amount','Method','Wallet','SMS ID','Note'], ...data.rows.map((r) => [r.settlement_at, r.direction, r.recipient_name, r.amount, r.method, r.wallet, r.sms_id, r.note])].map((r) => r.map(esc).join(',')).join('\n'); const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); a.download = 'cash-settlements.csv'; a.click() }
  const totals = useMemo(() => data?.totals ?? { total_in: 0, total_out: 0, net: 0 }, [data])
  return <PanelShell><section className="page-head"><div><h2>💵 {t('تسوية كاش SMS', 'Cash SMS settlement')}</h2><p className="page-sub">{t('سجّل الكاش الخارج من رسائل السحب حسب الاسم والمبلغ والطريقة.', 'Reconcile cash-out SMS by recipient, amount, and method.')}</p></div><button className="btn-ghost btn-sm" onClick={exportCsv} disabled={!data}><Download size={15}/> {t('تصدير', 'Export')}</button></section>
    <div className="filter-bar transaction-filter-toolbar"><label>{t('من', 'From')}<input className="login-input" type="date" value={from} onChange={(e) => setFrom(e.target.value)}/></label><label>{t('إلى', 'To')}<input className="login-input" type="date" value={to} onChange={(e) => setTo(e.target.value)}/></label><button className="btn-ghost btn-sm" onClick={() => void load()} disabled={busy}><RefreshCw size={14} className={busy ? 'spin' : ''}/> {t('تحديث', 'Refresh')}</button></div>
    <div className="kpi-grid"><div className="kpi-card"><div className="kpi-value">{money(totals.total_in, 'EGP')}</div><div className="kpi-label">{t('إجمالي الداخل', 'Total in')}</div></div><div className="kpi-card"><div className="kpi-value">{money(totals.total_out, 'EGP')}</div><div className="kpi-label">{t('إجمالي الخارج', 'Total out')}</div></div><div className="kpi-card"><div className="kpi-value">{money(totals.net, 'EGP')}</div><div className="kpi-label">{t('الصافي', 'Net')}</div></div></div>
    {err && <div className="card warn">{err}</div>}{can('reports', 'can_edit') || can('settlements', 'can_edit') || can('sms_live', 'can_edit') ? <section className="card cash-settlement-form"><div className="recent-head"><h3>{t('إضافة حركة كاش', 'Add cash movement')}</h3></div><form className="settlement-payment-form" onSubmit={add}><select className="login-input" value={form.direction} onChange={(e) => setForm({ ...form, direction: e.target.value })}><option value="out">{t('خارج / تم التسليم','Out / delivered')}</option><option value="in">{t('داخل / تم الاستلام','In / received')}</option></select><input className="login-input" required placeholder={t('اسم المستلم','Recipient name')} value={form.recipient_name} onChange={(e) => setForm({ ...form, recipient_name: e.target.value })}/><input className="login-input" required type="number" min="0.01" step="0.01" placeholder={t('المبلغ','Amount')} value={form.amount} onChange={(e) => setForm({ ...form, amount: e.target.value })}/><select className="login-input" value={form.method} onChange={(e) => setForm({ ...form, method: e.target.value })}><option>Cash</option><option>Orange Cash</option><option>Vodafone Cash</option><option>WE Pay</option><option>Etisalat Cash</option><option>USDT</option><option>Bank</option></select><input className="login-input mono" placeholder={t('رقم المحفظة (اختياري)','Wallet (optional)')} value={form.wallet} onChange={(e) => setForm({ ...form, wallet: e.target.value })}/><input className="login-input" type="number" min="1" placeholder="SMS ID (optional)" value={form.sms_id} onChange={(e) => setForm({ ...form, sms_id: e.target.value })}/><input className="login-input" placeholder={t('ملاحظة','Note')} value={form.note} onChange={(e) => setForm({ ...form, note: e.target.value })}/><button className="btn-primary" disabled={busy}>{busy ? t('جارٍ الحفظ…','Saving…') : t('حفظ الحركة','Save movement')}</button></form></section> : null}
    <section className="card recent-card"><div className="recent-head"><h3>{t('سجل التسويات', 'Settlement ledger')}</h3><span className="cell-sub">{data?.rows.length ?? 0} {t('حركة', 'movements')}</span></div><div className="table-wrap"><table className="data-table"><thead><tr><th>{t('التاريخ','Date')}</th><th>{t('الاتجاه','Direction')}</th><th>{t('الاسم','Name')}</th><th>{t('المبلغ','Amount')}</th><th>{t('الطريقة','Method')}</th><th>{t('المحفظة','Wallet')}</th><th>SMS ID</th><th>{t('بواسطة','By')}</th></tr></thead><tbody>{(data?.rows ?? []).map((r) => <tr key={r.id}><td className="mono">{new Date(r.settlement_at).toLocaleString('en-GB', { timeZone: 'Africa/Cairo', dateStyle: 'short', timeStyle: 'short' })}</td><td><span className={`pay-status-badge ${r.direction === 'in' ? 'st-paid' : 'st-pending'}`}>{r.direction === 'in' ? t('داخل','IN') : t('خارج','OUT')}</span></td><td>{r.recipient_name}</td><td className="mono">{money(r.amount, 'EGP')}</td><td>{r.method}</td><td className="mono">{r.wallet ?? '—'}</td><td className="mono">{r.sms_id ?? '—'}</td><td>{r.created_by ?? '—'}</td></tr>)}{!data?.rows.length && <tr><td colSpan={8} className="executive-empty">{t('لا توجد حركات في النطاق','No movements in range')}</td></tr>}</tbody></table></div></section>
  </PanelShell>
}
