import { FormEvent, useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { MessageCircle, Plus, Send, Users, X } from 'lucide-react'
import PanelShell from '../components/PanelShell'
import UserLogo from '../components/UserLogo'
import { api, ApiError } from '../lib/api'
import { useLocale } from '../lib/locale'

type User = { id: string; username: string; display_name: string | null; role: string }
type Message = { id: number; room_id: string; sender_id: string; body: string; created_at: string; edited_at?: string | null }
type Room = { id: string; name: string; kind: 'direct'|'group'; members: (User & {last_read_at:string|null})[]; last_message: Message|null; unread: number }
type ChatData = { me: string; users: User[]; rooms: Room[]; presence: {user_id:string;last_seen_at:string}[] }
const when = (value?: string|null) => value ? new Date(value).toLocaleString([], { month:'short', day:'numeric', hour:'2-digit', minute:'2-digit' }) : ''

export default function InternalChat() {
  const { t } = useLocale(); const [data,setData]=useState<ChatData|null>(null); const [roomId,setRoomId]=useState<string|null>(null); const [messages,setMessages]=useState<Message[]>([]); const [draft,setDraft]=useState(''); const [error,setError]=useState<string|null>(null); const [creating,setCreating]=useState(false); const [group,setGroup]=useState(false); const [name,setName]=useState(''); const [selected,setSelected]=useState<string[]>([]); const [sending,setSending]=useState(false); const endRef=useRef<HTMLDivElement>(null)
  const load=useCallback(async(silent=false)=>{try{const next=await api<ChatData>('/api/chat');setData(next);setError(null);setRoomId((current)=>current??next.rooms[0]?.id??null)}catch(e){if(!silent)setError(e instanceof ApiError?e.code:t('تعذر تحميل المحادثات.','Could not load conversations.'))}},[t])
  const loadMessages=useCallback(async(id:string,silent=false)=>{try{const res=await api<{messages:Message[]}>(`/api/chat/rooms/${id}/messages`);setMessages(res.messages);if(!silent)setTimeout(()=>endRef.current?.scrollIntoView({behavior:'smooth'}),20)}catch(e){if(!silent)setError(e instanceof ApiError?e.code:'messages_failed')}},[])
  useEffect(()=>{void load();const timer=setInterval(()=>void load(true),5000);const presence=setInterval(()=>void api('/api/chat/presence',{method:'POST'}).catch(()=>{}),20000);return()=>{clearInterval(timer);clearInterval(presence)}},[load])
  useEffect(()=>{if(!roomId){setMessages([]);return}void loadMessages(roomId);const timer=setInterval(()=>void loadMessages(roomId,true),3000);return()=>clearInterval(timer)},[roomId,loadMessages])
  useEffect(()=>{endRef.current?.scrollIntoView()},[messages.length])
  const room=data?.rooms.find((r)=>r.id===roomId); const users=useMemo(()=>data?.users.filter((u)=>u.id!==data.me)??[],[data]); const userMap=useMemo(()=>new Map(data?.users.map((u)=>[u.id,u])??[]),[data]); const presence=useMemo(()=>new Map(data?.presence.map((p)=>[p.user_id,p.last_seen_at])??[]),[data]); const online=(id:string)=>Date.now()-Date.parse(presence.get(id)??'')<60000
  const send=async(e:FormEvent)=>{e.preventDefault();if(!roomId||!draft.trim()||sending)return;const body=draft.trim();setDraft('');setSending(true);try{const res=await api<{message:Message}>(`/api/chat/rooms/${roomId}/messages`,{method:'POST',body:JSON.stringify({body})});setMessages((current)=>[...current,res.message]);void load(true)}catch(e){setDraft(body);setError(e instanceof ApiError?e.code:'send_failed')}finally{setSending(false)}}
  const create=async()=>{if(!selected.length)return;try{const res=await api<{room_id:string}>('/api/chat/rooms',{method:'POST',body:JSON.stringify({kind:group?'group':'direct',name,member_ids:group?selected:selected.slice(0,1)})});setCreating(false);setSelected([]);setName('');await load();setRoomId(res.room_id)}catch(e){setError(e instanceof ApiError?e.code:'create_failed')}}
  return <PanelShell><section className="page-head"><h2>{t('محادثات الفريق','Internal Chat')}</h2><p className="page-sub">{t('رسائل داخلية آمنة، محادثات فردية ومجموعات مع حالة القراءة والاتصال.','Secure team messages, direct chats and groups with read and online status.')}</p></section>
    {error&&<div className="card warn">{error}</div>}
    <section className="team-chat card">
      <aside className="chat-rooms"><div className="chat-panel-head"><strong>{t('المحادثات','Conversations')}</strong><button className="btn-primary btn-sm" onClick={()=>setCreating(true)}><Plus size={15}/>{t('جديد','New')}</button></div>{data?.rooms.map((r)=><button key={r.id} className={`chat-room${roomId===r.id?' active':''}`} onClick={()=>setRoomId(r.id)}><span className="chat-room-icon">{r.kind==='group'?<Users size={18}/>:<MessageCircle size={18}/>}</span><span><b>{r.name}</b><small>{r.last_message?.body??t('ابدأ المحادثة','Start the conversation')}</small></span>{r.unread>0&&<em>{r.unread}</em>}</button>)}{data&&data.rooms.length===0&&<div className="chat-empty">{t('لا توجد محادثات بعد.','No conversations yet.')}</div>}</aside>
      <main className="chat-main">{room?<><header className="chat-title"><div><strong>{room.name}</strong><span>{room.members.map((m)=>m.display_name??m.username).join(', ')}</span></div><div className="chat-presence">{room.members.filter((m)=>m.id!==data?.me).map((m)=><span key={m.id} className={online(m.id)?'online':''}>● {m.display_name??m.username}</span>)}</div></header><div className="chat-messages">{messages.map((m)=>{const mine=m.sender_id===data?.me;const sender=userMap.get(m.sender_id);const seen=mine&&room.members.filter((x)=>x.id!==data?.me).some((x)=>x.last_read_at&&x.last_read_at>=m.created_at);return <article key={m.id} className={`chat-message${mine?' mine':''}`}>{!mine&&<UserLogo username={sender?.username} name={sender?.display_name}/>}<div><b>{mine?t('أنت','You'):(sender?.display_name??sender?.username??t('مستخدم','User'))}</b><p>{m.body}</p><small>{when(m.created_at)}{mine&&` · ${seen?t('تمت المشاهدة','Seen'):t('تم الإرسال','Sent')}`}</small></div></article>})}<div ref={endRef}/></div><form className="chat-compose" onSubmit={send}><textarea value={draft} onChange={(e)=>setDraft(e.target.value)} maxLength={4000} placeholder={t('اكتب رسالة…','Write a message…')} onKeyDown={(e)=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();e.currentTarget.form?.requestSubmit()}}}/><button className="btn-primary" disabled={!draft.trim()||sending}><Send size={17}/>{t('إرسال','Send')}</button></form></>:<div className="chat-empty chat-empty-main"><MessageCircle size={38}/>{t('اختر محادثة أو ابدأ محادثة جديدة.','Choose a conversation or start a new one.')}</div>}</main>
    </section>
    {creating&&<div className="proof-overlay" onClick={()=>setCreating(false)}><section className="card chat-create" onClick={(e)=>e.stopPropagation()}><div className="chat-panel-head"><strong>{t('محادثة جديدة','New conversation')}</strong><button className="btn-ghost btn-sm" onClick={()=>setCreating(false)}><X size={17}/></button></div><div className="filter-pills"><button className={`pill${!group?' active':''}`} onClick={()=>{setGroup(false);setSelected(selected.slice(0,1))}}>{t('فردية','Direct')}</button><button className={`pill${group?' active':''}`} onClick={()=>setGroup(true)}>{t('مجموعة','Group')}</button></div>{group&&<input className="login-input" value={name} onChange={(e)=>setName(e.target.value)} placeholder={t('اسم المجموعة','Group name')}/>}<div className="chat-user-picker">{users.map((u)=><label key={u.id}><input type={group?'checkbox':'radio'} checked={selected.includes(u.id)} onChange={(e)=>setSelected(e.target.checked?(group?[...selected,u.id]:[u.id]):selected.filter((id)=>id!==u.id))}/><UserLogo username={u.username} name={u.display_name}/><span><b>{u.display_name??u.username}</b><small>{u.role}</small></span><i className={online(u.id)?'online':''}>●</i></label>)}</div><button className="btn-primary" disabled={!selected.length||(group&&!name.trim())} onClick={()=>void create()}>{t('إنشاء المحادثة','Create conversation')}</button></section></div>}
  </PanelShell>
}
