import { useCallback, useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { RefreshCw } from 'lucide-react'
import { api } from '../lib/api'
import { depositTime, money } from '../lib/deposits'
import { useLocale } from '../lib/locale'

interface Sms { id: number; received_at: string | null; amount: number | null; balance_after: number | null; sms_category: string | null; sender_name: string | null; sender_number: string | null; receiver_number: string | null; confirmed_wallet_number?: string | null; wallet_number?: string | null; provider: string | null; matched: boolean | null }
interface Payout { maven_id: number; amount: number | null; status: string; account_name: string | null; mobile_no: string | null; pay_by: string | null; first_seen_at: string | null }
interface Wallet { wallet: string; received: number; out: number; balance: number | null; receivedCount: number; outCount: number; latestAt: string | null; provider: string | null }

const cairoDate = () => new Intl.DateTimeFormat('en-CA', { timeZone: 'Africa/Cairo' }).format(new Date())

export default function P2PTv() {
  const { t } = useLocale(); const [sms, setSms] = useState<Sms[]>([]); const [payouts, setPayouts] = useState<Payout[]>([]); const [updated, setUpdated] = useState<Date | null>(null); const [loading, setLoading] = useState(true)
  const load = useCallback(async () => { setLoading(true); const day = cairoDate(); const [smsResult, payoutResult] = await Promise.allSettled([api<{ rows: Sms[] }>(`/api/sms?from=${day}&to=${day}&limit=500`), api<{ rows: Payout[] }>(`/api/payouts?from=${day}&to=${day}&limit=500`)]); if (smsResult.status === 'fulfilled') setSms(smsResult.value.rows ?? []); if (payoutResult.status === 'fulfilled') setPayouts(payoutResult.value.rows ?? []); setUpdated(new Date()); setLoading(false) }, [])
  useEffect(() => { void load(); const timer = window.setInterval(() => void load(), 10_000); return () => window.clearInterval(timer) }, [load])
  const wallets = useMemo(() => { const map = new Map<string, Wallet>(); for (const row of sms) { const wallet = row.confirmed_wallet_number ?? row.wallet_number ?? row.receiver_number; if (!wallet) continue; const item = map.get(wallet) ?? { wallet, received: 0, out: 0, balance: null, receivedCount: 0, outCount: 0, latestAt: null, provider: row.provider }; const amount = Number(row.amount ?? 0); if (row.sms_category === 'withdrawal') { item.out += amount; item.outCount += 1 } else { item.received += amount; item.receivedCount += 1 } if (row.balance_after != null && (!item.latestAt || Date.parse(String(row.received_at)) > Date.parse(item.latestAt))) { item.balance = Number(row.balance_after); item.latestAt = row.received_at } item.provider = item.provider ?? row.provider; map.set(wallet, item) } return [...map.values()].sort((a, b) => (b.balance ?? 0) - (a.balance ?? 0)) }, [sms])
  const incoming = sms.filter((row) => row.sms_category !== 'withdrawal'); const outgoing = sms.filter((row) => row.sms_category === 'withdrawal'); const payoutAmount = payouts.filter((row) => ['PAID', 'APPROVED', 'SUCCESS', 'COMPLETED'].includes(String(row.status).toUpperCase())).reduce((sum, row) => sum + Number(row.amount ?? 0), 0); const currentBalance = wallets.reduce((sum, row) => sum + Number(row.balance ?? 0), 0)
  return <div className="p2p-tv-page"><header className="p2p-tv-head"><div><span className="reports-eyebrow">P2P · LIVE WALLET CONTROL</span><h1>{t('لوحة P2P الحية', 'P2P Live TV')}</h1><p>{t('رصيد المحافظ والاستلام والسحب من SMS مباشرة.', 'Live wallet balances, received funds, and payout SMS.')}</p></div><div className="p2p-tv-head-actions"><span className="live-dot"><span className="ld"/>{t('مباشر','Live')}</span><span className="mono">{updated ? updated.toLocaleTimeString('en-US', { timeZone: 'Africa/Cairo' }) : '—'}</span><button className="btn-ghost btn-sm" onClick={() => void load()} disabled={loading}><RefreshCw size={15} className={loading ? 'spin' : ''}/>{t('تحديث','Refresh')}</button><Link className="btn-ghost btn-sm" to="/">✕</Link></div></header>
    <section className="p2p-tv-kpis"><article><small>{t('الرصيد الحالي للمحافظ','Current wallet balance')}</small><strong>{money(currentBalance,'EGP')}</strong><span>{wallets.length} {t('محفظة','wallets')}</span></article><article><small>{t('إجمالي الاستلام اليوم','Total received today')}</small><strong>{money(incoming.reduce((s, r) => s + Number(r.amount ?? 0), 0),'EGP')}</strong><span>{incoming.length} SMS</span></article><article><small>{t('إجمالي الخارج SMS','Total outbound SMS')}</small><strong>{money(outgoing.reduce((s, r) => s + Number(r.amount ?? 0), 0),'EGP')}</strong><span>{outgoing.length} SMS</span></article><article><small>{t('السحوبات المعتمدة','Approved payouts')}</small><strong>{money(payoutAmount,'EGP')}</strong><span>{payouts.length} {t('طلب','requests')}</span></article></section>
    <main className="p2p-tv-columns"><section className="p2p-tv-card"><div className="p2p-tv-card-head"><div><h2>📥 {t('استلام المحافظ','Wallet receiving')}</h2><p>{t('الوارد والرصيد الحالي لكل محفظة.', 'Inbound and current balance per wallet.')}</p></div><span className="p2p-tv-count">{wallets.length}</span></div><div className="p2p-wallet-list">{wallets.map((row) => <article key={row.wallet}><div className="p2p-wallet-top"><strong className="mono">{row.wallet}</strong><span className="p2p-live-balance"><i/> {money(row.balance,'EGP')}</span></div><div className="p2p-wallet-stats"><span>{t('استلام','In')} <b className="positive-text">{money(row.received,'EGP')}</b> · {row.receivedCount} SMS</span><span>{row.provider ?? '—'}</span></div><div className="p2p-wallet-meta"><span>{t('خارج','Out')} {money(row.out,'EGP')} · {row.outCount} SMS</span><time>{row.latestAt ? depositTime({ first_seen_at: row.latestAt }) : '—'}</time></div></article>)}{!wallets.length && <p className="executive-empty">{t('لا توجد محافظ نشطة اليوم.','No active wallets today.')}</p>}</div></section>
      <section className="p2p-tv-card payout"><div className="p2p-tv-card-head"><div><h2>📤 {t('كارت payout SMS','Payout SMS card')}</h2><p>{t('السحب الخارج مع الرصيد الحي للمحفظة.', 'Outbound payout SMS with live wallet balance.')}</p></div><span className="p2p-tv-count">{outgoing.length}</span></div><div className="p2p-payout-list">{outgoing.slice(0, 40).map((row) => <article key={row.id}><div className="p2p-wallet-top"><strong>{row.sender_name ?? row.sender_number ?? t('مستلم غير معروف','Unknown recipient')}</strong><span className="mono">{money(row.amount,'EGP')}</span></div><div className="p2p-wallet-stats"><span className="mono">SMS #{row.id} · {row.receiver_number ?? row.wallet_number ?? '—'}</span><span>{row.provider ?? '—'}</span></div><div className="p2p-wallet-meta"><span className="p2p-live-balance"><i/> {money(row.balance_after,'EGP')}</span><time>{depositTime({ first_seen_at: row.received_at })}</time></div></article>)}{!outgoing.length && <p className="executive-empty">{t('لا توجد رسائل سحب اليوم.','No payout SMS today.')}</p>}</div></section></main>
  </div>
}
