import { useCallback, useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { RefreshCw } from 'lucide-react'
import { api } from '../lib/api'
import { depositTime, money } from '../lib/deposits'
import { useLocale } from '../lib/locale'

interface Sms { id: number; received_at: string | null; device_name?: string | null; sim_slot?: number | null; amount: number | null; balance_after: number | null; sms_category: string | null; sender_name: string | null; sender_number: string | null; receiver_number: string | null; confirmed_wallet_number?: string | null; wallet_number?: string | null; provider: string | null; matched: boolean | null; sms_first_line?: string | null; raw_sms?: string | null }
interface Payout { maven_id: number; amount: number | null; status: string; account_name: string | null; mobile_no: string | null; pay_by: string | null; first_seen_at: string | null }
interface Wallet { wallet: string; received: number; out: number; balance: number | null; receivedCount: number; outCount: number; latestAt: string | null; provider: string | null; device: string | null; simSlot: number | null }

const cairoDate = () => new Intl.DateTimeFormat('en-CA', { timeZone: 'Africa/Cairo' }).format(new Date())
const cairoMonthStart = () => `${cairoDate().slice(0, 7)}-01`
const isCairoToday = (value: string | null) => value ? new Intl.DateTimeFormat('en-CA', { timeZone: 'Africa/Cairo' }).format(new Date(value)) === cairoDate() : false

export default function P2PTv() {
  const { t } = useLocale(); const today = cairoDate(); const [sms, setSms] = useState<Sms[]>([]); const [payouts, setPayouts] = useState<Payout[]>([]); const [updated, setUpdated] = useState<Date | null>(null); const [loading, setLoading] = useState(true)
  const [dateRange, setDateRange] = useState({ from: cairoMonthStart(), to: today }); const [draftFrom, setDraftFrom] = useState(cairoMonthStart()); const [draftTo, setDraftTo] = useState(today); const [providerFilter, setProviderFilter] = useState(''); const [walletFilter, setWalletFilter] = useState(''); const [flowFilter, setFlowFilter] = useState('all')
  const load = useCallback(async () => { setLoading(true); const [smsResult, payoutResult] = await Promise.allSettled([api<{ rows: Sms[] }>(`/api/sms?from=${dateRange.from}&to=${dateRange.to}&limit=5000`), api<{ rows: Payout[] }>(`/api/payouts?from=${dateRange.to}&to=${dateRange.to}&limit=500`)]); if (smsResult.status === 'fulfilled') setSms(smsResult.value.rows ?? []); if (payoutResult.status === 'fulfilled') setPayouts(payoutResult.value.rows ?? []); setUpdated(new Date()); setLoading(false) }, [dateRange.from, dateRange.to])
  useEffect(() => { void load(); const timer = window.setInterval(() => void load(), 10_000); return () => window.clearInterval(timer) }, [load])
  const wallets = useMemo(() => { const map = new Map<string, Wallet>(); for (const row of sms) { const wallet = row.confirmed_wallet_number ?? row.wallet_number ?? row.receiver_number; if (!wallet) continue; const item = map.get(wallet) ?? { wallet, received: 0, out: 0, balance: null, receivedCount: 0, outCount: 0, latestAt: null, provider: row.provider, device: row.device_name ?? null, simSlot: row.sim_slot ?? null }; const amount = Number(row.amount ?? 0); if (row.sms_category === 'withdrawal') { item.out += amount; item.outCount += 1 } else { item.received += amount; item.receivedCount += 1 } if (row.balance_after != null && (!item.latestAt || Date.parse(String(row.received_at)) > Date.parse(item.latestAt))) { item.balance = Number(row.balance_after); item.latestAt = row.received_at; item.device = row.device_name ?? item.device; item.simSlot = row.sim_slot ?? item.simSlot } item.provider = item.provider ?? row.provider; map.set(wallet, item) } return [...map.values()].sort((a, b) => (b.balance ?? 0) - (a.balance ?? 0)) }, [sms])
  const providers = [...new Set(sms.map((row) => row.provider).filter(Boolean) as string[])].sort(); const walletNumbers = [...new Set(sms.map((row) => row.confirmed_wallet_number ?? row.wallet_number ?? row.receiver_number).filter(Boolean) as string[])].sort(); const filteredSms = sms.filter((row) => (!providerFilter || row.provider === providerFilter) && (!walletFilter || (row.confirmed_wallet_number ?? row.wallet_number ?? row.receiver_number) === walletFilter) && (flowFilter === 'all' || (flowFilter === 'in' ? row.sms_category !== 'withdrawal' : row.sms_category === 'withdrawal'))); const filteredWallets = wallets.filter((row) => (!providerFilter || row.provider === providerFilter) && (!walletFilter || row.wallet === walletFilter)); const todaySms = filteredSms.filter((row) => isCairoToday(row.received_at)); const incoming = todaySms.filter((row) => row.sms_category !== 'withdrawal'); const outgoing = todaySms.filter((row) => row.sms_category === 'withdrawal'); const payoutAmount = payouts.filter((row) => ['PAID', 'APPROVED', 'SUCCESS', 'COMPLETED'].includes(String(row.status).toUpperCase())).reduce((sum, row) => sum + Number(row.amount ?? 0), 0); const currentBalance = filteredWallets.reduce((sum, row) => sum + Number(row.balance ?? 0), 0)
  return <div className="p2p-tv-page"><header className="p2p-tv-head"><div><span className="reports-eyebrow">P2P · LIVE WALLET CONTROL</span><h1>{t('لوحة P2P الحية', 'P2P Live TV')}</h1><p>{t('رصيد المحافظ والاستلام والسحب من SMS مباشرة.', 'Live wallet balances, received funds, and payout SMS.')}</p></div><div className="p2p-tv-head-actions"><span className="live-dot"><span className="ld"/>{t('مباشر','Live')}</span><span className="mono">{updated ? updated.toLocaleTimeString('en-US', { timeZone: 'Africa/Cairo' }) : '—'}</span><button className="btn-ghost btn-sm" onClick={() => void load()} disabled={loading}><RefreshCw size={15} className={loading ? 'spin' : ''}/>{t('تحديث','Refresh')}</button><Link className="btn-ghost btn-sm" to="/">✕</Link></div></header>
    <form className="p2p-tv-filter-bar" onSubmit={(event) => { event.preventDefault(); if (draftFrom <= draftTo) setDateRange({ from: draftFrom, to: draftTo }) }}><label><span>{t('من تاريخ','From')}</span><input type="date" value={draftFrom} max={draftTo} onChange={(event) => setDraftFrom(event.target.value)} /></label><label><span>{t('إلى تاريخ','To')}</span><input type="date" value={draftTo} min={draftFrom} max={today} onChange={(event) => setDraftTo(event.target.value)} /></label><label><span>{t('المزوّد','Provider')}</span><select value={providerFilter} onChange={(event) => setProviderFilter(event.target.value)}><option value="">{t('كل المزوّدين','All providers')}</option>{providers.map((provider) => <option key={provider} value={provider}>{provider}</option>)}</select></label><label><span>{t('المحفظة','Wallet')}</span><select value={walletFilter} onChange={(event) => setWalletFilter(event.target.value)}><option value="">{t('كل المحافظ','All wallets')}</option>{walletNumbers.map((wallet) => <option key={wallet} value={wallet}>{wallet}</option>)}</select></label><label><span>{t('نوع الحركة','Flow')}</span><select value={flowFilter} onChange={(event) => setFlowFilter(event.target.value)}><option value="all">{t('الكل','All')}</option><option value="in">{t('وارد','Incoming')}</option><option value="out">{t('خارج','Outgoing')}</option></select></label><button className="btn-primary btn-sm" type="submit">{loading ? t('جارٍ التحديث…','Loading…') : t('تطبيق الفلتر','Apply filters')}</button><button className="btn-ghost btn-sm" type="button" onClick={() => { setDraftFrom(cairoMonthStart()); setDraftTo(today); setDateRange({ from: cairoMonthStart(), to: today }); setProviderFilter(''); setWalletFilter(''); setFlowFilter('all') }}>{t('مسح','Clear')}</button><small className="p2p-tv-filter-range">{dateRange.from} → {dateRange.to}</small></form>
    <section className="p2p-tv-kpis"><article><small>{t('الرصيد الحالي للمحافظ','Current wallet balance')}</small><strong>{money(currentBalance,'EGP')}</strong><span>{filteredWallets.length} {t('محفظة','wallets')}</span></article><article><small>{t('إجمالي الاستلام اليوم','Total received today')}</small><strong>{money(incoming.reduce((s, r) => s + Number(r.amount ?? 0), 0),'EGP')}</strong><span>{incoming.length} SMS</span></article><article><small>{t('إجمالي الخارج SMS','Total outbound SMS')}</small><strong>{money(outgoing.reduce((s, r) => s + Number(r.amount ?? 0), 0),'EGP')}</strong><span>{outgoing.length} SMS</span></article><article><small>{t('السحوبات المعتمدة','Approved payouts')}</small><strong>{money(payoutAmount,'EGP')}</strong><span>{payouts.length} {t('طلب','requests')}</span></article></section>
    <main className="p2p-live-sms-columns"><section className="p2p-tv-card p2p-sms-card incoming"><div className="p2p-tv-card-head"><div><h2>🟢 {t('SMS وارد مباشر','Live SMS In')}</h2><p>{t('كل رسائل الاستلام اليوم مع المحفظة والرصيد.', 'Every incoming SMS today with wallet and balance.')}</p></div><span className="p2p-tv-count">{incoming.length}</span></div><div className="p2p-sms-list">{incoming.map((row) => <article key={row.id}><div className="p2p-wallet-top"><strong>{row.sender_name ?? row.sender_number ?? t('مرسل غير معروف','Unknown sender')}</strong><span className="p2p-live-balance"><i/> {money(row.amount,'EGP')}</span></div><div className="p2p-wallet-stats"><span className="mono">SMS #{row.id} · {row.confirmed_wallet_number ?? row.wallet_number ?? row.receiver_number ?? '—'}</span><span>{row.provider ?? '—'}</span></div><div className="p2p-wallet-meta"><span>{t('الرصيد بعد العملية','Balance after')} {money(row.balance_after,'EGP')}</span><time>{depositTime({ first_seen_at: row.received_at })}</time></div>{(row.sms_first_line || row.raw_sms) && <div className="p2p-sms-raw">{row.sms_first_line ?? row.raw_sms}</div>}</article>)}{!incoming.length && <p className="executive-empty">{t('لا توجد رسائل واردة اليوم.','No incoming SMS today.')}</p>}</div></section><section className="p2p-tv-card p2p-sms-card outgoing"><div className="p2p-tv-card-head"><div><h2>🔴 {t('SMS خارج مباشر','Live SMS Out')}</h2><p>{t('كل رسائل السحب اليوم مع المحفظة والرصيد.', 'Every outgoing SMS today with wallet and balance.')}</p></div><span className="p2p-tv-count">{outgoing.length}</span></div><div className="p2p-sms-list">{outgoing.map((row) => <article key={row.id}><div className="p2p-wallet-top"><strong>{row.sender_name ?? row.sender_number ?? t('مستلم غير معروف','Unknown recipient')}</strong><span className="mono">{money(row.amount,'EGP')}</span></div><div className="p2p-wallet-stats"><span className="mono">SMS #{row.id} · {row.confirmed_wallet_number ?? row.wallet_number ?? row.receiver_number ?? '—'}</span><span>{row.provider ?? '—'}</span></div><div className="p2p-wallet-meta"><span className="p2p-live-balance"><i/> {money(row.balance_after,'EGP')}</span><time>{depositTime({ first_seen_at: row.received_at })}</time></div>{(row.sms_first_line || row.raw_sms) && <div className="p2p-sms-raw">{row.sms_first_line ?? row.raw_sms}</div>}</article>)}{!outgoing.length && <p className="executive-empty">{t('لا توجد رسائل خارجة اليوم.','No outgoing SMS today.')}</p>}</div></section></main>
    <main className="p2p-tv-columns"><section className="p2p-tv-card"><div className="p2p-tv-card-head"><div><h2>📥 {t('استلام المحافظ','Wallet receiving')}</h2><p>{t('الوارد خلال الفترة والرصيد الحالي من آخر SMS لكل محفظة.', 'Received in the selected range and current balance from the latest SMS per wallet.')}</p></div><span className="p2p-tv-count">{filteredWallets.length}</span></div><div className="p2p-wallet-list">{filteredWallets.map((row) => <article key={row.wallet}><div className="p2p-wallet-top"><strong className="mono">{row.wallet}</strong><span className="p2p-live-balance"><i/> {money(row.balance,'EGP')}</span></div><div className="p2p-wallet-stats"><span>{t('وارد الفترة','Range in')} <b className="positive-text">{money(row.received,'EGP')}</b> · {row.receivedCount} SMS</span><span>{row.provider ?? '—'}</span></div><div className="p2p-wallet-meta"><span>{t('خارج الفترة','Range out')} {money(row.out,'EGP')} · {row.outCount} SMS</span><time>{row.latestAt ? `${t('آخر SMS','Last SMS')} ${depositTime({ first_seen_at: row.latestAt })}` : t('لا يوجد رصيد في SMS','No SMS balance')}</time></div></article>)}{!filteredWallets.length && <p className="executive-empty">{t('لا توجد محافظ في الفترة المحددة.','No wallets in the selected range.')}</p>}</div></section>
      <section className="p2p-tv-card payout"><div className="p2p-tv-card-head"><div><h2>📤 {t('كارت payout SMS','Payout SMS card')}</h2><p>{t('السحب الخارج مع الرصيد الحي للمحفظة.', 'Outbound payout SMS with live wallet balance.')}</p></div><span className="p2p-tv-count">{outgoing.length}</span></div><div className="p2p-payout-list">{outgoing.map((row) => <article key={row.id}><div className="p2p-wallet-top"><strong>{row.sender_name ?? row.sender_number ?? t('مستلم غير معروف','Unknown recipient')}</strong><span className="mono">{money(row.amount,'EGP')}</span></div><div className="p2p-wallet-stats"><span className="mono">SMS #{row.id} · {row.receiver_number ?? row.wallet_number ?? '—'}</span><span>{row.provider ?? '—'}</span></div><div className="p2p-wallet-meta"><span className="p2p-live-balance"><i/> {money(row.balance_after,'EGP')}</span><time>{depositTime({ first_seen_at: row.received_at })}</time></div></article>)}{!outgoing.length && <p className="executive-empty">{t('لا توجد رسائل سحب اليوم.','No payout SMS today.')}</p>}</div></section></main>
    <section className="p2p-live-balance-strip">{filteredWallets.map((row) => <div key={row.wallet}><span className="p2p-live-balance"><i/> {t('الرصيد الحي','Live balance')}</span><strong className="mono">SIM {row.simSlot ?? '—'} · {row.device ?? '—'}</strong><b>{money(row.balance,'EGP')}</b></div>)}</section>
  </div>
}
