import { useCallback, useEffect, useState } from 'react'
import PanelShell from '../components/PanelShell'
import { api, ApiError } from '../lib/api'
import { useAuth } from '../auth/AuthContext'
import { useLocale } from '../lib/locale'

interface Method { id: string; method_code: string; method_name: string; channel_type: string; is_active: boolean; sort_order: number }
interface Account { id: string; payment_method_id: string; account_number: string; account_name: string | null; iban: string | null; bank_name: string | null; currency: string | null; country_code: string | null; device_name: string | null; label: string | null; is_active: boolean }
const emptyAccount = { account_number: '', label: '', device_name: '', bank_name: '' }

export default function PaymentMethods() {
  const { t } = useLocale(); const { can } = useAuth()
  const [data, setData] = useState<{ methods: Method[]; accounts: Account[] } | null>(null)
  const [error, setError] = useState<string | null>(null); const [open, setOpen] = useState<string | null>(null)
  const [account, setAccount] = useState(emptyAccount); const [newMethod, setNewMethod] = useState({ method_code: '', method_name: '', channel_type: 'sms_device' })
  const editable = can('payment_methods', 'can_edit'); const create = can('payment_methods', 'can_create')
  const load = useCallback(async () => { try { setData(await api('/api/payment-methods')); setError(null) } catch (e) { setError(e instanceof ApiError && e.status === 403 ? t('لا تملك صلاحية طرق الدفع.', 'You do not have payment-method permission.') : t('تعذر التحميل.', 'Unable to load.')) } }, [t])
  useEffect(() => { void load() }, [load])
  const toggle = async (method: Method) => { try { await api(`/api/payment-methods/${method.id}`, { method: 'PATCH', body: JSON.stringify({ is_active: !method.is_active }) }); await load() } catch { setError(t('تعذر الحفظ.', 'Unable to save.')) } }
  const addMethod = async (e: React.FormEvent) => { e.preventDefault(); try { await api('/api/payment-methods', { method: 'POST', body: JSON.stringify(newMethod) }); setNewMethod({ method_code: '', method_name: '', channel_type: 'sms_device' }); await load() } catch { setError(t('تعذر إضافة الطريقة.', 'Unable to add method.')) } }
  const addAccount = async (e: React.FormEvent) => { e.preventDefault(); if (!open) return; try { await api(`/api/payment-methods/${open}/accounts`, { method: 'POST', body: JSON.stringify(account) }); setAccount(emptyAccount); setOpen(null); await load() } catch { setError(t('تعذر إضافة الحساب.', 'Unable to add account.')) } }
  const toggleAccount = async (row: Account) => { try { await api(`/api/payment-methods/accounts/${row.id}`, { method: 'PATCH', body: JSON.stringify({ is_active: !row.is_active }) }); await load() } catch { setError(t('تعذر الحفظ.', 'Unable to save.')) } }
  return <PanelShell><section className="page-head"><h2>{t('طرق الدفع والحسابات', 'Payment methods & accounts')}</h2><p className="page-sub">{t('طبقة عرض وإدارة فقط؛ لا تستبدل خرائط SMS التشغيلية.', 'Reference catalogue only; it does not replace operational SMS mapping.')}</p></section>
    {error && <div className="card warn">{error}</div>}
    {create && <form className="card control-row" onSubmit={addMethod}><strong>{t('إضافة طريقة', 'Add method')}</strong><input className="login-input" required placeholder="CODE" value={newMethod.method_code} onChange={(e) => setNewMethod({ ...newMethod, method_code: e.target.value })}/><input className="login-input" required placeholder={t('الاسم', 'Name')} value={newMethod.method_name} onChange={(e) => setNewMethod({ ...newMethod, method_name: e.target.value })}/><select className="login-input" value={newMethod.channel_type} onChange={(e) => setNewMethod({ ...newMethod, channel_type: e.target.value })}><option value="sms_device">SMS device</option><option value="bank_transfer">Bank transfer</option><option value="other">Other</option></select><button className="btn-primary btn-sm">{t('إضافة', 'Add')}</button></form>}
    {!data && <p className="sidebar-hint">{t('جار التحميل…', 'Loading…')}</p>}
    {data?.methods.map((method) => { const rows = data.accounts.filter((row) => row.payment_method_id === method.id); return <section className="card recent-card" key={method.id}><div className="recent-head"><div><h3>{method.method_name} <span className="cell-sub mono">{method.method_code} · {method.channel_type}</span></h3></div><div className="control-row">{editable && <button className="btn-ghost btn-sm" onClick={() => void toggle(method)}>{method.is_active ? t('إيقاف', 'Disable') : t('تفعيل', 'Enable')}</button>}{create && <button className="btn-primary btn-sm" onClick={() => setOpen(open === method.id ? null : method.id)}>{t('إضافة حساب', 'Add account')}</button>}</div></div>
      {open === method.id && <form className="control-row" onSubmit={addAccount}><input required className="login-input" placeholder={t('رقم الحساب', 'Account number')} value={account.account_number} onChange={(e) => setAccount({ ...account, account_number: e.target.value })}/><input className="login-input" placeholder={t('تسمية', 'Label')} value={account.label} onChange={(e) => setAccount({ ...account, label: e.target.value })}/><input className="login-input" placeholder={t('الجهاز', 'Device')} value={account.device_name} onChange={(e) => setAccount({ ...account, device_name: e.target.value })}/><button className="btn-primary btn-sm">{t('حفظ', 'Save')}</button></form>}
      <div className="table-wrap"><table className="data-table"><thead><tr><th>{t('الرقم', 'Number')}</th><th>{t('التسمية', 'Label')}</th><th>{t('الجهاز', 'Device')}</th><th>{t('الحالة', 'Status')}</th><th /></tr></thead><tbody>{rows.length ? rows.map((row) => <tr key={row.id}><td className="mono">{row.account_number}</td><td>{row.label ?? row.account_name ?? '—'}</td><td className="mono">{row.device_name ?? '—'}</td><td><span className={`pay-status-badge ${row.is_active ? 'st-paid' : 'st-dim'}`}>{row.is_active ? t('نشط', 'Active') : t('موقوف', 'Disabled')}</span></td><td>{editable && <button className="btn-ghost btn-sm" onClick={() => void toggleAccount(row)}>{row.is_active ? t('إيقاف', 'Disable') : t('تفعيل', 'Enable')}</button>}</td></tr>) : <tr><td colSpan={5} className="sidebar-hint">{t('لا توجد حسابات.', 'No accounts.')}</td></tr>}</tbody></table></div></section> })}
  </PanelShell>
}
