import { useCallback, useEffect, useState } from 'react'
import PanelShell from '../components/PanelShell'
import { api, ApiError } from '../lib/api'
import { useAuth } from '../auth/AuthContext'
import { useLocale } from '../lib/locale'

type RequestRow = { id:string; wallet_number:string; amount:number; device:string; merchant_name:string|null; note:string|null; status:string; requested_by:string|null; approved_by:string|null; webhook_status:number|null; webhook_error:string|null; created_at:string }
export default function PayoutRequests() {
  const { can } = useAuth(); const { t } = useLocale(); const [rows,setRows]=useState<RequestRow[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [busy,setBusy]=useState<string|null>(null); const [form,setForm]=useState({wallet_number:'',amount:'',device:'ont1',note:''})
  const load=useCallback(async()=>{setLoading(true);try{const r=await api<{data:RequestRow[]}>('/api/payout-requests');setRows(r.data??[]);setError(null)}catch(e){setError(e instanceof ApiError&&e.status===403?t('لا تملك صلاحية عرض الطلبات.','You do not have permission to view requests.'):t('تعذر تحميل الطلبات.','Failed to load requests.'))}finally{setLoading(false)}},[])
  useEffect(()=>{void load();const iv=window.setInterval(()=>void load(),8000);return()=>window.clearInterval(iv)},[load])
  const create=async(e:React.FormEvent)=>{e.preventDefault();setBusy('create');try{await api('/api/payout-requests',{method:'POST',body:JSON.stringify({...form,amount:Number(form.amount)})});setForm({wallet_number:'',amount:'',device:'ont1',note:''});await load()}catch(e){setError(e instanceof ApiError?e.message:t('فشل إنشاء الطلب.','Failed to create request.'))}finally{setBusy(null)}}
  const decide=async(id:string,action:'approve'|'reject')=>{setBusy(id);try{await api(`/api/payout-requests/${id}/decision`,{method:'POST',body:JSON.stringify({action})});await load()}catch(e){setError(e instanceof ApiError?e.message:t('فشل تنفيذ الإجراء.','Action failed.'))}finally{setBusy(null)}}
  return <PanelShell><section className="page-head"><div><h2>📤 {t('طلبات السحب اليدوية','Manual payout requests')}</h2><p className="page-sub">{t('طلب → موافقة صريحة → تنفيذ USSD على الجهاز','Request → explicit approval → USSD execution on device')}</p></div></section>{error&&<div className="card warn">{error}</div>}{can('payouts','can_create')&&<form className="card payout-request-form" onSubmit={create}><h3>{t('طلب سحب جديد','New payout request')}</h3><input className="login-input" required placeholder={t('رقم المحفظة','Wallet number')} value={form.wallet_number} onChange={e=>setForm({...form,wallet_number:e.target.value})}/><input className="login-input" required type="number" min="1" placeholder={t('المبلغ EGP','Amount EGP')} value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/><select className="login-input" value={form.device} onChange={e=>setForm({...form,device:e.target.value})}>{['ont1','ont2','ont3','ont4','ont5','ont6','ont7'].map(d=><option key={d}>{d}</option>)}</select><input className="login-input" placeholder={t('ملاحظة','Note')} value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/><button className="btn-primary" disabled={busy==='create'}>{t('إنشاء الطلب','Create request')}</button></form>}<section className="card recent-card"><div className="recent-head"><h3>{t('الطلبات','Requests')} ({rows.length})</h3></div>{loading&&!rows.length?<p className="sidebar-hint">{t('جارٍ التحميل…','Loading…')}</p>:<div className="table-wrap"><table className="data-table"><thead><tr><th>ID</th><th>{t('المحفظة','Wallet')}</th><th>{t('المبلغ','Amount')}</th><th>{t('الجهاز','Device')}</th><th>{t('الحالة','Status')}</th><th>{t('مقدم بواسطة','Requested by')}</th><th>{t('إجراء','Action')}</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td className="mono">{r.id.slice(0,8)}</td><td className="mono">{r.wallet_number}</td><td className="mono">{r.amount.toFixed(2)} EGP</td><td className="mono">{r.device}</td><td><span className={`pay-status-badge ${r.status==='completed'||r.status==='executing'?'st-paid':r.status==='failed'||r.status==='rejected'?'st-declined':'st-pending'}`}>{r.status}</span>{r.webhook_error&&<div className="cell-sub danger-text">{r.webhook_error}</div>}</td><td>{r.requested_by??'—'}</td><td>{r.status==='pending'&&can('payouts','can_approve')&&<div className="row-actions"><button className="btn-primary btn-sm" disabled={busy===r.id} onClick={()=>void decide(r.id,'approve')}>{t('موافقة','Approve')}</button><button className="btn-ghost danger btn-sm" disabled={busy===r.id} onClick={()=>void decide(r.id,'reject')}>{t('رفض','Reject')}</button></div>}</td></tr>)}</tbody></table></div>}</section></PanelShell>
}
