import { useState } from 'react'
import PanelShell from '../components/PanelShell'
import { api } from '../lib/api'
import { money } from '../lib/deposits'
import { useLocale } from '../lib/locale'

type Candidate = { tx_id: number; ontarget_ref: string | null; amount: number; status: string; sender_name: string | null; merchant: string | null; score: number; signals: { name_exact: boolean; within_10_minutes: boolean; seconds_difference: number | null } }
type Merchant = { id: string; name: string; callback_url: string }

export default function ReplayLab() {
  const { t } = useLocale(); const [smsId, setSmsId] = useState(''); const [amount, setAmount] = useState(''); const [sender, setSender] = useState(''); const [receivedAt, setReceivedAt] = useState(''); const [candidates, setCandidates] = useState<Candidate[]>([]); const [msg, setMsg] = useState(''); const [err, setErr] = useState('')
  const [merchants, setMerchants] = useState<Merchant[]>([]); const [merchantId, setMerchantId] = useState(''); const [payload, setPayload] = useState('{\n  "event": "transaction.updated",\n  "reference": ""\n}'); const [confirm, setConfirm] = useState('')
  const run = async (url: string, body?: unknown) => { setErr(''); setMsg(''); try { const result = await api<{ candidates: Candidate[]; unique_strict_match: boolean }>(url, { method: 'POST', ...(body ? { body: JSON.stringify(body) } : {}) }); setCandidates(result.candidates); setMsg(result.unique_strict_match ? t('وجدت مطابقة صارمة وحيدة — لم يتم ربطها.', 'One strict match found — nothing was linked.') : t('اكتملت المعاينة دون أي تغيير.', 'Preview completed without changes.')) } catch { setErr(t('تعذرت المعاينة.', 'Preview failed.')) } }
  const loadWebhooks = async () => { try { const result = await api<{ merchants: Merchant[] }>('/api/replay/webhooks'); setMerchants(result.merchants); if (result.merchants[0]) setMerchantId(result.merchants[0].id) } catch { setErr(t('تعذر تحميل Webhooks.', 'Failed to load webhooks.')) } }
  const replayWebhook = async () => { setErr(''); setMsg(''); try { const parsed = JSON.parse(payload); const result = await api<{ ok: boolean; status: number | null; idempotency_key: string }> (`/api/replay/webhooks/${merchantId}`, { method: 'POST', body: JSON.stringify({ payload: parsed, confirmation: confirm }) }); setMsg(`${result.ok ? '✓' : '✗'} HTTP ${result.status ?? '—'} · ${result.idempotency_key}`); setConfirm('') } catch { setErr(t('فشل Webhook replay أو التأكيد غير صحيح.', 'Webhook replay failed or confirmation is invalid.')) } }
  return <PanelShell><section className="page-head"><h2>{t('مختبر Replay والمحاكاة', 'Replay & simulation lab')}</h2><p className="page-sub">{t('معاينة SMS آمنة، وإعادة Webhook يدوية مؤكدة ومسجلة.', 'Safe SMS previews and explicitly confirmed, audited webhook replay.')}</p></section>{err && <div className="card warn">{err}</div>}{msg && <div className="card">{msg}</div>}
    <section className="card recent-card"><h3>SMS Replay</h3><div className="control-row"><input className="login-input" value={smsId} onChange={(e) => setSmsId(e.target.value)} placeholder="SMS ID" /><button className="btn-primary btn-sm" disabled={!smsId} onClick={() => void run(`/api/replay/sms/${smsId}/replay`)}>{t('معاينة الرسالة', 'Replay preview')}</button></div></section>
    <section className="card recent-card"><h3>SMS Simulator</h3><div className="binance-grid"><input className="login-input" type="number" value={amount} onChange={(e) => setAmount(e.target.value)} placeholder={t('المبلغ', 'Amount')} /><input className="login-input" value={sender} onChange={(e) => setSender(e.target.value)} placeholder={t('اسم المرسل', 'Sender name')} /><input className="login-input" type="datetime-local" value={receivedAt} onChange={(e) => setReceivedAt(e.target.value)} /></div><button className="btn-primary btn-sm" style={{ marginTop: 12 }} disabled={!amount || !receivedAt} onClick={() => void run('/api/replay/sms/simulate', { amount: Number(amount), sender_name: sender, received_at: new Date(receivedAt).toISOString() })}>{t('تشغيل Dry Run', 'Run dry run')}</button>
      {candidates.length > 0 && <div className="table-wrap"><table className="data-table"><thead><tr><th>TRX</th><th>{t('المبلغ', 'Amount')}</th><th>{t('المرسل', 'Sender')}</th><th>{t('الحالة', 'Status')}</th><th>{t('النتيجة', 'Score')}</th></tr></thead><tbody>{candidates.map((row) => <tr key={row.tx_id}><td className="mono">{row.ontarget_ref ?? row.tx_id}</td><td className="mono">{money(row.amount, 'EGP')}</td><td>{row.sender_name ?? '—'}</td><td>{row.status}</td><td className="mono">{row.score}%<div className="cell-sub">name {row.signals.name_exact ? '✓' : '✗'} · 10m {row.signals.within_10_minutes ? '✓' : '✗'}</div></td></tr>)}</tbody></table></div>}
    </section>
    <section className="card recent-card"><div className="recent-head"><h3>Webhook Replay</h3><button className="btn-ghost btn-sm" onClick={() => void loadWebhooks()}>{t('تحميل التجار', 'Load merchants')}</button></div><div className="binance-grid"><select className="login-input" value={merchantId} onChange={(e) => setMerchantId(e.target.value)}><option value="">{t('اختر التاجر', 'Select merchant')}</option>{merchants.map((row) => <option value={row.id} key={row.id}>{row.name}</option>)}</select><input className="login-input" value={confirm} onChange={(e) => setConfirm(e.target.value)} placeholder="REPLAY WEBHOOK" /></div><textarea className="login-input" rows={8} value={payload} onChange={(e) => setPayload(e.target.value)} style={{ width: '100%', marginTop: 12 }} /><button className="btn-primary btn-sm" disabled={!merchantId || confirm !== 'REPLAY WEBHOOK'} onClick={() => void replayWebhook()}>{t('إرسال Webhook الآن', 'Send webhook now')}</button></section>
  </PanelShell>
}
