import { useCallback, useEffect, useMemo, useState } from 'react'
import PanelShell from '../components/PanelShell'
import { api, ApiError } from '../lib/api'
import { money } from '../lib/deposits'
import { useAuth } from '../auth/AuthContext'
import { useLocale } from '../lib/locale'

interface Bucket { count: number; amount: number }
interface Report { from: string | null; to: string | null; hero: { ngpayPaid: number; approvedPayouts: number; net: number; payoutsUnclassified: boolean }; unassigned: { count: number; amount: number }; depositStatuses: Record<string, Bucket>; payoutStatuses: Record<string, Bucket>; byMaster: { master: string; count: number; amount: number }[]; byMethod: { method: string; master: string; count: number; amount: number }[]; daily: { date: string; deposits: number; payouts: number; count: number }[]; includesPayFuture: boolean }
const depositOrder = ['PENDING', 'PAID', 'APPROVED', 'DECLINED', 'EXPIRED', 'EXPIRED_LOCAL', 'UNDERPAID']

export default function Reports() {
  const { t } = useLocale(); const { can } = useAuth()
  const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const [report, setReport] = useState<Report | null>(null); const [err, setErr] = useState<string | null>(null)
  const load = useCallback(async () => { try { const q = new URLSearchParams(); if (from) q.set('from', from); if (to) q.set('to', to); setReport(await api<Report>(`/api/reports?${q}`)); setErr(null) } catch (e) { setErr(e instanceof ApiError && e.status === 403 ? t('لا تملك صلاحية عرض التقارير.', 'You do not have permission to view reports.') : t('تعذر تحميل التقرير.', 'Unable to load report.')) } }, [from, to, t])
  useEffect(() => { void load() }, [load])
  const deposited = useMemo(() => Object.values(report?.depositStatuses ?? {}).reduce((sum, bucket) => sum + bucket.amount, 0), [report])
  const paidOut = useMemo(() => Object.values(report?.payoutStatuses ?? {}).reduce((sum, bucket) => sum + bucket.amount, 0), [report])
  const exportCsv = () => { const q = new URLSearchParams(); if (from) q.set('from', from); if (to) q.set('to', to); window.location.assign(`/api/reports/export?${q}`) }
  return <PanelShell><section className="page-head"><h2>{t('التقارير', 'Reports')}</h2><p className="page-sub">{t('ملخصات الإيداع والسحب حسب النطاق الزمني والحالة والتاجر والطريقة.', 'Deposit and payout summaries by time range, status, merchant, and method.')}</p></section>
    <div className="filter-bar report-filters"><label className="filter-field">{t('من', 'From')} <input className="login-input" type="date" value={from} onChange={(e) => setFrom(e.target.value)}/></label><label className="filter-field">{t('إلى', 'To')} <input className="login-input" type="date" value={to} onChange={(e) => setTo(e.target.value)}/></label><button className="btn-ghost btn-sm" onClick={() => { setFrom(''); setTo('') }}>{t('كل الوقت', 'All time')}</button>{can('reports', 'can_export') && <button className="btn-primary btn-sm" onClick={exportCsv}>CSV / Excel</button>}</div>
    {report?.includesPayFuture && <div className="card warn">⚠️ {t('تشمل بيانات اختبار (PayFuture). لا تفسّر الإجماليات كإيرادات حقيقية بالكامل.', 'Includes test data (PayFuture). Do not interpret totals as wholly real revenue.')}</div>}
    {err && <div className="card warn">{err}</div>}{!report && !err && <p className="sidebar-hint">{t('جار الحساب…', 'Calculating…')}</p>}
    {report && <>
      <section className="card recent-card"><div className="recent-head"><h3>{t('صافي رصيد NGPay (حي)', 'NGPay net balance (live)')}</h3><span className="cell-sub">{t('إيداعات PAID/APPROVED ناقص السحوبات المقبولة', 'PAID/APPROVED deposits minus approved payouts')}</span></div>
        <div className="kpi-grid"><div className="kpi-card"><div className="kpi-value">{money(report.hero.net, 'EGP')}</div><div className="kpi-label">{t('الصافي', 'Net')}</div></div><div className="kpi-card"><div className="kpi-value">{money(report.hero.ngpayPaid, 'EGP')}</div><div className="kpi-label">{t('إيداعات NGPay المدفوعة', 'NGPay paid deposits')}</div></div><div className="kpi-card"><div className="kpi-value">{money(report.hero.approvedPayouts, 'EGP')}</div><div className="kpi-label">{t('سحوبات مقبولة', 'Approved payouts')}</div></div></div>
        {report.hero.payoutsUnclassified && <p className="page-sub">⚠️ {t('أرقام السحب غير مصنّفة حسب المزوّد (لا يوجد عمود master_merchant في جدول السحوبات) — تُخصم بالكامل من NGPay كافتراض.', 'Payout totals are not split per provider (no master_merchant column on payouts) — deducted wholly from NGPay as an assumption.')}</p>}
      </section>
      {report.unassigned.count > 0 && <div className="card warn">🔎 {t(`${report.unassigned.count} معاملة بدون تصنيف master merchant (${money(report.unassigned.amount, 'EGP')}) — تحتاج مراجعة.`, `${report.unassigned.count} transaction(s) without a master merchant (${money(report.unassigned.amount, 'EGP')}) — needs review.`)}</div>}
      <div className="kpi-grid"><div className="kpi-card"><div className="kpi-value">{money(deposited, 'EGP')}</div><div className="kpi-label">{t('كل الإيداعات', 'All deposits')}</div></div><div className="kpi-card"><div className="kpi-value">{money(paidOut, 'EGP')}</div><div className="kpi-label">{t('كل السحوبات', 'All payouts')}</div></div><div className="kpi-card"><div className="kpi-value">{report.byMaster.length}</div><div className="kpi-label">{t('Master merchants', 'Master merchants')}</div></div><div className="kpi-card"><div className="kpi-value">{report.byMethod.length}</div><div className="kpi-label">{t('طرق الدفع', 'Payment methods')}</div></div></div>
      <section className="card recent-card"><div className="recent-head"><h3>{t('الإيداعات حسب الحالة', 'Deposits by status')}</h3></div><div className="table-wrap"><table className="data-table"><thead><tr><th>{t('الحالة', 'Status')}</th><th>{t('العدد', 'Count')}</th><th>{t('القيمة', 'Amount')}</th></tr></thead><tbody>{depositOrder.map((status) => { const row = report.depositStatuses[status] ?? { count: 0, amount: 0 }; return <tr key={status}><td className="mono">{status}</td><td className="mono">{row.count}</td><td className="mono">{money(row.amount, 'EGP')}</td></tr> })}</tbody></table></div></section>
      <section className="card recent-card"><div className="recent-head"><h3>{t('السحوبات حسب الحالة', 'Payouts by status')}</h3></div><div className="table-wrap"><table className="data-table"><thead><tr><th>{t('الحالة', 'Status')}</th><th>{t('العدد', 'Count')}</th><th>{t('القيمة', 'Amount')}</th></tr></thead><tbody>{Object.entries(report.payoutStatuses).map(([status, row]) => <tr key={status}><td className="mono">{status}</td><td className="mono">{row.count}</td><td className="mono">{money(row.amount, 'EGP')}</td></tr>)}</tbody></table></div></section>
      <section className="card recent-card"><div className="recent-head"><h3>{t('تقسيم Master merchant', 'Master merchant breakdown')}</h3></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Master</th><th>{t('العدد', 'Count')}</th><th>{t('الإجمالي', 'Total')}</th></tr></thead><tbody>{report.byMaster.map((row) => <tr key={row.master}><td>{row.master}</td><td className="mono">{row.count}</td><td className="mono">{money(row.amount, 'EGP')}</td></tr>)}</tbody></table></div></section>
      <section className="card recent-card"><div className="recent-head"><h3>{t('طرق الدفع', 'Payment methods')}</h3></div><div className="table-wrap"><table className="data-table"><thead><tr><th>{t('الطريقة', 'Method')}</th><th>Master</th><th>{t('العدد', 'Count')}</th><th>{t('الإجمالي', 'Total')}</th></tr></thead><tbody>{report.byMethod.map((row) => <tr key={`${row.method}-${row.master}`}><td>{row.method}</td><td>{row.master}</td><td className="mono">{row.count}</td><td className="mono">{money(row.amount, 'EGP')}</td></tr>)}</tbody></table></div></section>
    </>}</PanelShell>
}
