import { useCallback, useEffect, useMemo, useState } from 'react'
import { CalendarDays, Clock3, LogIn, LogOut, RefreshCw, WalletCards } from 'lucide-react'
import PanelShell from '../components/PanelShell'
import { api, ApiError } from '../lib/api'
import { money } from '../lib/deposits'
import { useLocale } from '../lib/locale'

type Staff = { user_id: string; username: string; display_name: string | null; role: string; active_session: { wallet_number: string | null; checked_in_at: string } | null; sessions: number; hours: number; transaction_count: number; approved_count: number; transaction_amount: number; approved_amount: number; sms_count: number; wallets: string[] }
type Session = { id: string; user_id: string; wallet_number: string | null; checked_in_at: string; checked_out_at: string | null; note: string | null }
type Attendance = { from: string; to: string; wallet: string | null; users: Staff[]; sessions: Session[] }
const today = () => new Date().toISOString().slice(0, 10)

export default function StaffAttendance() {
  const { t, locale } = useLocale()
  const [from, setFrom] = useState(today); const [to, setTo] = useState(today); const [wallet, setWallet] = useState(''); const [selected, setSelected] = useState<string | null>(null); const [data, setData] = useState<Attendance | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null)
  const load = useCallback(async () => { setBusy(true); try { const q = new URLSearchParams({ from, to }); if (wallet) q.set('wallet', wallet); setData(await api<Attendance>(`/api/reports/attendance?${q}`)); setError(null) } catch (e) { setError(e instanceof ApiError && e.status === 403 ? t('لا تملك صلاحية التقرير.', 'You do not have report permission.') : t('تعذر تحميل الحضور.', 'Unable to load attendance.')) } finally { setBusy(false) } }, [from, to, wallet, t])
  useEffect(() => { void load() }, [load])
  const action = async (userId: string, kind: 'check-in' | 'check-out') => { setBusy(true); try { await api(`/api/reports/attendance/${kind}`, { method: 'POST', body: JSON.stringify({ user_id: userId, wallet_number: wallet || undefined }) }); await load() } catch (e) { setError(e instanceof ApiError ? e.code : 'attendance_failed') } finally { setBusy(false) } }
  const wallets = useMemo(() => [...new Set((data?.users ?? []).flatMap((row) => row.wallets))].sort(), [data])
  const totals = useMemo(() => (data?.users ?? []).reduce((a, r) => ({ tx: a.tx + r.transaction_count, approved: a.approved + r.approved_count, amount: a.amount + r.approved_amount, sms: a.sms + r.sms_count, hours: a.hours + r.hours }), { tx: 0, approved: 0, amount: 0, sms: 0, hours: 0 }), [data])
  const monthly = from.slice(0, 7) !== to.slice(0, 7) ? t('نطاق مخصص', 'Custom range') : from.slice(8) === '01' && to.slice(8) === '01' ? t('شهري', 'Monthly') : t('يومي', 'Daily')
  return <PanelShell><section className="page-head"><div><h2>{t('حضور وأداء الفريق', 'Staff attendance & performance')}</h2><p className="page-sub">{t('تسجيل دخول وخروج كل agent/operator وربط ساعات العمل بالمحافظ والمعاملات والتدفق النقدي.', 'Check in/out every agent/operator and connect work hours to wallets, transactions, and cash flow.')}</p></div></section>
    <section className="card reports-filter-card"><div className="reports-scope-grid"><label>{t('من', 'From')}<input className="login-input" type="date" value={from} onChange={(e) => setFrom(e.target.value)} /></label><label>{t('إلى', 'To')}<input className="login-input" type="date" value={to} onChange={(e) => setTo(e.target.value)} /></label><label>{t('المحفظة', 'Wallet')}<select className="login-input" value={wallet} onChange={(e) => setWallet(e.target.value)}><option value="">{t('كل المحافظ', 'All wallets')}</option>{wallets.map((value) => <option key={value} value={value}>{value}</option>)}</select></label><button className="btn-ghost btn-sm reports-refresh" onClick={() => void load()} disabled={busy}><RefreshCw size={15} className={busy ? 'spin' : ''}/>{t('تحديث', 'Refresh')}</button><span className="reports-range"><CalendarDays size={14}/>{monthly}</span></div></section>
    {error && <div className="card warn">{error}</div>}
    <div className="reports-kpis live-financial-kpis"><article><span className="reports-kpi-icon"><Clock3 size={18}/></span><small>{t('ساعات العمل', 'Work hours')}</small><strong>{totals.hours.toFixed(1)}</strong><em>{t('ضمن النطاق', 'in selected range')}</em></article><article><span className="reports-kpi-icon"><WalletCards size={18}/></span><small>{t('المعاملات', 'Transactions')}</small><strong>{totals.tx}</strong><em>{totals.approved} {t('معتمدة', 'approved')}</em></article><article><span className="reports-kpi-icon positive"><WalletCards size={18}/></span><small>{t('التدفق النقدي المعتمد', 'Approved cash flow')}</small><strong>{money(totals.amount, 'EGP')}</strong><em>{totals.sms} SMS</em></article></div>
    <section className="card recent-card"><div className="recent-head"><div><h3>{t('وكلاء التشغيل', 'Operations staff')}</h3><span className="cell-sub">{t('الأزرار تسجل الحضور على الموظف والمحفظة المختارة.', 'Buttons record attendance for the selected staff member and wallet.')}</span></div></div><div className="table-wrap"><table className="data-table"><thead><tr><th>{t('الموظف', 'Staff')}</th><th>{t('الدور', 'Role')}</th><th>{t('الحضور', 'Attendance')}</th><th>{t('المحفظة', 'Wallet')}</th><th>{t('المعاملات', 'Transactions')}</th><th>{t('النقد المعتمد', 'Approved cash')}</th><th>{t('إجراء', 'Action')}</th></tr></thead><tbody>{(data?.users ?? []).map((row) => <tr key={row.user_id}><td><button className="btn-link" onClick={() => setSelected(selected === row.user_id ? null : row.user_id)}><strong>{row.display_name || row.username}</strong></button><div className="cell-sub mono">{row.username}</div></td><td className="mono">{row.role}</td><td>{row.active_session ? <span className="pay-status-badge st-paid">{t('داخل الآن', 'Checked in')} · {new Date(row.active_session.checked_in_at).toLocaleTimeString(locale)}</span> : <span className="pay-status-badge st-dim">{t('خارج', 'Checked out')}</span>}</td><td className="mono">{row.active_session?.wallet_number || wallet || '—'}</td><td className="mono">{row.transaction_count} <span className="cell-sub">/ {row.approved_count} paid</span></td><td className="mono">{money(row.approved_amount, 'EGP')}</td><td><button className={row.active_session ? 'btn-ghost btn-sm danger' : 'btn-primary btn-sm'} disabled={busy} onClick={() => void action(row.user_id, row.active_session ? 'check-out' : 'check-in')}>{row.active_session ? <><LogOut size={14}/> {t('خروج', 'Check out')}</> : <><LogIn size={14}/> {t('دخول', 'Check in')}</>}</button></td></tr>)}</tbody></table>{!data && !error && <div className="executive-empty">{t('جار التحميل…', 'Loading…')}</div>}</div></section>
    {selected && data && <section className="card recent-card"><div className="recent-head"><h3>{t('أيام الحضور', 'Attendance days')} · {data.users.find((row) => row.user_id === selected)?.display_name}</h3></div><div className="table-wrap"><table className="data-table"><thead><tr><th>{t('اليوم', 'Day')}</th><th>{t('دخول', 'Check-in')}</th><th>{t('خروج', 'Check-out')}</th><th>{t('الساعات', 'Hours')}</th><th>{t('المحفظة', 'Wallet')}</th></tr></thead><tbody>{data.sessions.filter((row) => row.user_id === selected).map((row) => { const end = row.checked_out_at ? new Date(row.checked_out_at) : new Date(); const hours = Math.max(0, (end.getTime() - new Date(row.checked_in_at).getTime()) / 3600000); return <tr key={row.id}><td className="mono">{new Date(row.checked_in_at).toLocaleDateString(locale)}</td><td className="mono">{new Date(row.checked_in_at).toLocaleTimeString(locale)}</td><td className="mono">{row.checked_out_at ? new Date(row.checked_out_at).toLocaleTimeString(locale) : <span className="pay-status-badge st-paid">{t('مفتوح', 'Open')}</span>}</td><td className="mono">{hours.toFixed(2)}</td><td className="mono">{row.wallet_number || '—'}</td></tr>})}</tbody></table></div></section>}
  </PanelShell>
}
