import { useCallback, useEffect, useMemo, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { CalendarDays, Clock3, Download, RefreshCw, WalletCards } from 'lucide-react'
import PanelShell from '../components/PanelShell'
import { api, ApiError } from '../lib/api'
import { money } from '../lib/deposits'
import { useLocale } from '../lib/locale'

type SessionMetrics = { transaction_count: number; transaction_amount: number; approved_count: number; approved_amount: number; automation_count: number; automation_amount: number; withdrawal_count: number; withdrawal_amount: number; wallet: string | null; balance_start: number | null; balance_end: number | null; net_balance: number | null }
type Session = { id: string; user_id: string; wallet_number: string | null; checked_in_at: string; checked_out_at: string | null; note: string | null; metrics?: SessionMetrics }
type Staff = { user_id: string; username: string; display_name: string | null; role: string; active_session: { wallet_number: string | null; checked_in_at: string } | null; sessions: number; hours: number; transaction_count: number; approved_count: number; transaction_amount: number; approved_amount: number; sms_count: number; wallets: string[]; session_reports?: Session[] }
type Attendance = { from: string; to: string; wallet: string | null; users: Staff[]; sessions: Session[] }
const cairoToday = () => new Intl.DateTimeFormat('en-CA', { timeZone: 'Africa/Cairo', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date())
const cairoTime = (value: string) => new Intl.DateTimeFormat(undefined, { timeZone: 'Africa/Cairo', dateStyle: 'short', timeStyle: 'short' }).format(new Date(value))

export default function StaffAttendance() {
  const { t } = useLocale()
  const [searchParams] = useSearchParams()
  const [from, setFrom] = useState(cairoToday); const [to, setTo] = useState(cairoToday); const [wallet, setWallet] = useState(''); const [agent, setAgent] = useState(() => searchParams.get('user') ?? ''); const [selected, setSelected] = useState<string | null>(() => searchParams.get('user')); const [data, setData] = useState<Attendance | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null)
  const load = useCallback(async () => { setBusy(true); try { const q = new URLSearchParams({ from, to }); if (wallet) q.set('wallet', wallet); if (agent) q.set('user_id', agent); setData(await api<Attendance>(`/api/reports/attendance?${q}`)); setError(null) } catch (e) { setError(e instanceof ApiError && e.status === 403 ? t('لا تملك صلاحية التقرير.', 'You do not have report permission.') : t('تعذر تحميل الحضور.', 'Unable to load attendance.')) } finally { setBusy(false) } }, [from, to, wallet, agent, t])
  useEffect(() => { void load() }, [load])
  const action = async (userId: string, kind: 'check-in' | 'check-out') => { setBusy(true); try { await api(`/api/reports/attendance/${kind}`, { method: 'POST', body: JSON.stringify({ user_id: userId, wallet_number: wallet || undefined }) }); await load() } catch (e) { setError(e instanceof ApiError ? e.code : 'attendance_failed') } finally { setBusy(false) } }
  const wallets = useMemo(() => [...new Set((data?.users ?? []).flatMap((row) => row.wallets))].sort(), [data])
  const totals = useMemo(() => (data?.users ?? []).reduce((a, r) => ({ tx: a.tx + r.transaction_count, approved: a.approved + r.approved_count, amount: a.amount + r.approved_amount, sms: a.sms + r.sms_count, hours: a.hours + r.hours }), { tx: 0, approved: 0, amount: 0, sms: 0, hours: 0 }), [data])
  const profile = useMemo(() => { const row = data?.users.find((item) => item.user_id === selected); if (!row) return null; return (row.session_reports ?? []).reduce((a, session) => { const m = session.metrics; return { ...a, approved: a.approved + Number(m?.approved_amount ?? 0), approvedCount: a.approvedCount + Number(m?.approved_count ?? 0), automation: a.automation + Number(m?.automation_amount ?? 0), automationCount: a.automationCount + Number(m?.automation_count ?? 0), withdrawals: a.withdrawals + Number(m?.withdrawal_amount ?? 0), withdrawalCount: a.withdrawalCount + Number(m?.withdrawal_count ?? 0), hours: a.hours + (new Date(session.checked_out_at ?? new Date().toISOString()).getTime() - new Date(session.checked_in_at).getTime()) / 3600000, start: m?.balance_start ?? a.start, end: m?.balance_end ?? a.end } }, { name: row.display_name || row.username, role: row.role, approved: 0, approvedCount: 0, automation: 0, automationCount: 0, withdrawals: 0, withdrawalCount: 0, hours: 0, start: null as number | null, end: null as number | null }) }, [data, selected])
  const exportCsv = () => {
    if (!data) return
    const esc = (value: unknown) => `"${String(value ?? '').replaceAll('"', '""')}"`
    const rows = [
      ['employee', 'username', 'role', 'check_in_cairo', 'check_out_cairo', 'wallet', 'hours', 'transaction_count', 'transaction_amount_egp', 'approved_count', 'approved_amount_egp', 'automation_count', 'automation_amount_egp', 'withdrawal_count', 'withdrawal_amount_egp', 'balance_start', 'balance_end', 'net_balance'],
      ...data.users.flatMap((row) => (row.session_reports ?? []).map((session) => [row.display_name || row.username, row.username, row.role, cairoTime(session.checked_in_at), session.checked_out_at ? cairoTime(session.checked_out_at) : '', session.metrics?.wallet ?? '', session.metrics ? ((new Date(session.checked_out_at ?? new Date().toISOString()).getTime() - new Date(session.checked_in_at).getTime()) / 3600000).toFixed(2) : '', session.metrics?.transaction_count ?? '', session.metrics?.transaction_amount?.toFixed(2) ?? '', session.metrics?.approved_count ?? '', session.metrics?.approved_amount?.toFixed(2) ?? '', session.metrics?.automation_count ?? '', session.metrics?.automation_amount?.toFixed(2) ?? '', session.metrics?.withdrawal_count ?? '', session.metrics?.withdrawal_amount?.toFixed(2) ?? '', session.metrics?.balance_start ?? '', session.metrics?.balance_end ?? '', session.metrics?.net_balance ?? ''])),
    ]
    const blob = new Blob([rows.map((row) => row.map(esc).join(',')).join('\n')], { type: 'text/csv;charset=utf-8' })
    const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `ont27-hr-${data.from}-${data.to}.csv`; link.click(); URL.revokeObjectURL(url)
  }
  const monthly = from.slice(0, 7) !== to.slice(0, 7) ? t('نطاق مخصص', 'Custom range') : from.slice(8) === '01' && to.slice(8) === '01' ? t('شهري', 'Monthly') : t('يومي', 'Daily')
  return <PanelShell><section className="page-head"><div><h2>{t('الموارد البشرية', 'HR workspace')}</h2><p className="page-sub">{t('حضور وانصراف كل agent/operator مع أداء المعاملات والتدفق النقدي حسب الموظف والمحفظة.', 'Check in/out every agent/operator with employee, wallet, transaction, and cash-flow performance.')}</p></div><button className="btn-ghost btn-sm" onClick={exportCsv} disabled={!data || busy}><Download size={15}/>{t('تصدير HR', 'Export HR')}</button></section>
    <section className="card reports-filter-card"><div className="reports-scope-grid"><label>{t('من', 'From')}<input className="login-input" type="date" value={from} onChange={(e) => setFrom(e.target.value)} /></label><label>{t('إلى', 'To')}<input className="login-input" type="date" value={to} onChange={(e) => setTo(e.target.value)} /></label><label>{t('Agent / Operator', 'Agent / Operator')}<select className="login-input" value={agent} onChange={(e) => { setAgent(e.target.value); setSelected(e.target.value || null) }}><option value="">{t('كل الموظفين', 'All staff')}</option>{(data?.users ?? []).map((row) => <option key={row.user_id} value={row.user_id}>{row.display_name || row.username} · {row.role}</option>)}</select></label><label>{t('المحفظة', 'Wallet')}<select className="login-input" value={wallet} onChange={(e) => setWallet(e.target.value)}><option value="">{t('كل المحافظ', 'All wallets')}</option>{wallets.map((value) => <option key={value} value={value}>{value}</option>)}</select></label><button className="btn-ghost btn-sm reports-refresh" onClick={() => void load()} disabled={busy}><RefreshCw size={15} className={busy ? 'spin' : ''}/>{t('تحديث', 'Refresh')}</button><span className="reports-range"><CalendarDays size={14}/>{monthly}</span></div></section>
    {error && <div className="card warn">{error}</div>}
    <div className="reports-kpis live-financial-kpis"><article><span className="reports-kpi-icon"><Clock3 size={18}/></span><small>{t('ساعات العمل', 'Work hours')}</small><strong>{totals.hours.toFixed(1)}</strong><em>{t('بتوقيت القاهرة', 'Cairo time')}</em></article><article><span className="reports-kpi-icon"><WalletCards size={18}/></span><small>{t('إجمالي المعاملات', 'Total transactions')}</small><strong>{totals.tx}</strong><em>{totals.approved} {t('معتمدة', 'approved')}</em></article><article><span className="reports-kpi-icon positive"><WalletCards size={18}/></span><small>{t('إجمالي المبلغ', 'Total amount')}</small><strong>{money((data?.users ?? []).reduce((sum, row) => sum + row.transaction_amount, 0), 'EGP')}</strong><em>{money(totals.amount, 'EGP')} {t('معتمد', 'approved')}</em></article></div>
    {profile && <section className="reports-kpis live-financial-kpis"><article><small>{profile.name} · {profile.role}</small><strong>{profile.hours.toFixed(2)}h</strong><em>{t('ساعات العمل', 'Work hours')}</em></article><article><small>{t('اعتمادات الموظف', 'Employee approvals')}</small><strong>{profile.approvedCount} · {money(profile.approved, 'EGP')}</strong><em>{t('المعاملات التي اعتمدها', 'Approved by employee')}</em></article><article><small>{t('الأتمتة', 'Automation')}</small><strong>{profile.automationCount} · {money(profile.automation, 'EGP')}</strong><em>{t('أثناء وقت العمل', 'During work time')}</em></article><article><small>{t('السحب / صافي الرصيد', 'Withdrawals / net balance')}</small><strong>{money(profile.withdrawals, 'EGP')}</strong><em>{money(profile.start, 'EGP')} → {money(profile.end, 'EGP')}</em></article></section>}
    <section className="card recent-card"><div className="recent-head"><div><h3>{t('وكلاء التشغيل', 'Operations staff')}</h3><span className="cell-sub">{t('الأزرار تسجل الحضور على الموظف والمحفظة المختارة.', 'Buttons record attendance for the selected staff member and wallet.')}</span></div></div><div className="table-wrap"><table className="data-table"><thead><tr><th>{t('الموظف', 'Staff')}</th><th>{t('الدور', 'Role')}</th><th>{t('الحضور', 'Attendance')}</th><th>{t('المحفظة', 'Wallet')}</th><th>{t('المعاملات', 'Transactions')}</th><th>{t('إجمالي المبلغ', 'Total amount')}</th><th>{t('إجراء', 'Action')}</th></tr></thead><tbody>{(data?.users ?? []).map((row) => <tr key={row.user_id}><td><button className="btn-link" onClick={() => setSelected(selected === row.user_id ? null : row.user_id)}><strong>{row.display_name || row.username}</strong></button><div className="cell-sub mono">{row.username}</div></td><td className="mono">{row.role}</td><td>{row.active_session ? <span className="pay-status-badge st-paid">{t('داخل الآن', 'Checked in')} · {cairoTime(row.active_session.checked_in_at)}</span> : <span className="pay-status-badge st-dim">{t('خارج', 'Checked out')}</span>}</td><td className="mono">{row.active_session?.wallet_number || wallet || '—'}</td><td className="mono">{row.transaction_count} <span className="cell-sub">/ {row.approved_count} paid</span></td><td className="mono">{money(row.transaction_amount, 'EGP')}</td><td><button className={row.active_session ? 'btn-ghost btn-sm danger' : 'btn-primary btn-sm'} disabled={busy} onClick={() => void action(row.user_id, row.active_session ? 'check-out' : 'check-in')}>{row.active_session ? <><span aria-hidden="true">🚪</span> {t('خروج', 'Check out')}</> : <><span aria-hidden="true">✅</span> {t('دخول', 'Check in')}</>}</button></td></tr>)}</tbody></table>{!data && !error && <div className="executive-empty">{t('جار التحميل…', 'Loading…')}</div>}</div></section>
    {selected && data && <section className="card recent-card"><div className="recent-head"><div><h3>{t('تقرير الوردية', 'Work-session report')} · {data.users.find((row) => row.user_id === selected)?.display_name}</h3><span className="cell-sub">{t('كل الأوقات بتوقيت القاهرة', 'All times are Cairo time')}</span></div></div><div className="table-wrap"><table className="data-table"><thead><tr><th>{t('دخول', 'Check-in')}</th><th>{t('خروج', 'Check-out')}</th><th>{t('الساعات', 'Hours')}</th><th>{t('المحفظة', 'Wallet')}</th><th>{t('كل المعاملات', 'All transactions')}</th><th>{t('اعتمد', 'Approved')}</th><th>{t('Automation', 'Automation')}</th><th>{t('السحب', 'Withdrawals')}</th><th>{t('الصافي', 'Net')}</th></tr></thead><tbody>{(data.users.find((row) => row.user_id === selected)?.session_reports ?? data.sessions.filter((row) => row.user_id === selected)).map((row) => { const end = row.checked_out_at ? new Date(row.checked_out_at) : new Date(); const hours = Math.max(0, (end.getTime() - new Date(row.checked_in_at).getTime()) / 3600000); const m = row.metrics; return <tr key={row.id}><td className="mono">{cairoTime(row.checked_in_at)}</td><td className="mono">{row.checked_out_at ? cairoTime(row.checked_out_at) : <span className="pay-status-badge st-paid">{t('مفتوح', 'Open')}</span>}</td><td className="mono">{hours.toFixed(2)}</td><td className="mono">{row.wallet_number || '—'}</td><td className="mono">{m ? `${m.transaction_count} · ${money(m.transaction_amount, 'EGP')}` : '—'}</td><td className="mono">{m ? `${m.approved_count} · ${money(m.approved_amount, 'EGP')}` : '—'}</td><td className="mono">{m ? `${m.automation_count} · ${money(m.automation_amount, 'EGP')}` : '—'}</td><td className="mono">{m ? `${m.withdrawal_count} · ${money(m.withdrawal_amount, 'EGP')}` : '—'}</td><td className="mono">{m ? money(m.net_balance, 'EGP') : '—'}</td></tr>})}</tbody></table></div></section>}
  </PanelShell>
}
