import { useCallback, useEffect, useMemo, useState } from 'react'
import PanelShell from '../components/PanelShell'
import { api, ApiError } from '../lib/api'
import { useAuth } from '../auth/AuthContext'
import { useLocale } from '../lib/locale'

type Task = { id:number; ticket_no:string|null; subject:string|null; description:string|null; action_requested:string|null; assigned_to:string|null; due_at:string|null; priority:string|null; ticket_status:string; created_at:string|null; opened_by:string|null }
type User = { id:string; username:string; display_name:string|null; role:string; active:boolean }
const DEFAULT_REFS = `23034864273\n23033548537\n23059439989\n23065872841\n23035202743\n23064486705\n23073269303\n23079904039\n23079682187\n23085683233\n23082650551\n23102073969\n23099386031\n23081310281\n23089422001\n23066173747\n23114212171\n23109709453\n23113755807\n23114223039\n23119330811\n23121369081\n23117463413`

export default function TeamTasks() {
  const { t } = useLocale(); const { user } = useAuth()
  const manager = ['owner','admin','super_admin','operations_admin'].includes(user?.role ?? '')
  const [tasks,setTasks] = useState<Task[]>([]); const [users,setUsers] = useState<User[]>([]); const [refs,setRefs] = useState(DEFAULT_REFS)
  const [assignee,setAssignee] = useState(''); const [action,setAction] = useState('Investigate transaction and update support ticket')
  const [due,setDue] = useState(''); const [priority,setPriority] = useState('medium'); const [category,setCategory] = useState('support'); const [all,setAll] = useState(manager)
  const [busy,setBusy] = useState(false); const [error,setError] = useState<string|null>(null); const [toast,setToast] = useState<string|null>(null)
  const load = useCallback(async () => { try { const [ticketRes,userRes] = await Promise.all([api<{rows:Task[]}>(`/api/tickets?limit=200${all?'':'&mine=1'}`), api<{rows:User[]}>('/api/tickets/assignees')]); setTasks(ticketRes.rows); setUsers(userRes.rows); setError(null) } catch (e) { setError(e instanceof ApiError ? e.code : 'load_failed') } }, [all])
  useEffect(()=>{ void load(); const id=window.setInterval(()=>void load(),15000); return ()=>window.clearInterval(id) },[load])
  const operators = useMemo(()=>users.filter((u)=>u.role==='operator'||u.role==='operations_admin'),[users])
  const create = async () => { const lines=refs.split(/\r?\n/).map((x)=>x.trim()).filter(Boolean); if (!lines.length) return; setBusy(true); setError(null); try { for (let i=0;i<lines.length;i++) { const ref=lines[i]; const owner=assignee==='split' ? (i%2===0 ? 'Ahmed' : 'ahmedmano.solly') : assignee || null; await api('/api/tickets',{method:'POST',body:JSON.stringify({subject:`${category} · ${ref}`,description:`Provider reference: ${ref}`,action_requested:action,assigned_to:owner,due_at:due||null,priority,task_type:category})}) } setRefs(''); setToast(`${lines.length} ${t('مهمة أُضيفت للفريق','tasks assigned to the team')}`); window.setTimeout(()=>setToast(null),3500); await load() } catch(e) { setError(e instanceof ApiError ? e.code : 'create_failed') } finally { setBusy(false) } }
  const update = async (id:number, patch:Record<string,unknown>) => { try { await api(`/api/tickets/${id}`,{method:'PATCH',body:JSON.stringify(patch)}); await load() } catch(e) { setError(e instanceof ApiError ? e.code : 'update_failed') } }
  return <PanelShell><section className="page-head"><div><h2>🗂️ {t('مهام فريق الدعم','Team support tasks')}</h2><p className="page-sub">{t('أضف معاملات أو طلبات دعم، حدّد الإجراء والموعد، وأسندها مباشرة للمشغّل.','Add transaction/support work, set the requested action and deadline, and assign it directly to an operator.')}</p></div></section>
    {toast&&<div className="team-task-toast" role="status">🔔 {toast}</div>}{error&&<div className="card warn">{error}</div>}
    <section className="card team-task-create"><div className="recent-head"><h3>{t('إضافة مهام (لصق قائمة)', 'Add tasks (paste a list)')}</h3><span className="cell-sub">{t('كل سطر يصبح تذكرة مستقلة','Each line becomes a separate ticket')}</span></div><textarea className="login-input team-task-textarea" value={refs} onChange={(e)=>setRefs(e.target.value)} placeholder="23059439989" rows={6}/><div className="filter-bar"><select className="filter-select" value={category} onChange={(e)=>setCategory(e.target.value)}><option value="support">Support</option><option value="transaction">Transaction issue</option><option value="sms">SMS reconciliation</option><option value="payout">Payout</option><option value="complaint">Complaint</option></select><select className="filter-select" value={assignee} onChange={(e)=>setAssignee(e.target.value)}><option value="">{t('بدون إسناد','Unassigned')}</option><option value="split">Ahmed + Ahmed Mano (split)</option>{operators.map((o)=><option key={o.username} value={o.username}>{o.display_name||o.username}</option>)}</select><input className="login-input" value={action} onChange={(e)=>setAction(e.target.value)} placeholder={t('الإجراء المطلوب','Requested action')}/><input className="login-input" type="datetime-local" value={due} onChange={(e)=>setDue(e.target.value)}/><select className="filter-select" value={priority} onChange={(e)=>setPriority(e.target.value)}><option value="high">High</option><option value="medium">Medium</option><option value="normal">Normal</option><option value="low">Low</option></select><button className="btn-primary" disabled={busy||!refs.trim()} onClick={()=>void create()}>{busy?t('جارٍ الإضافة…','Adding…'):t('إضافة للفريق','Assign to team')}</button></div></section>
    <section className="card recent-card"><div className="recent-head"><div><h3>{t('قائمة العمل','Work queue')}</h3><span className="cell-sub">{tasks.length} {t('مهمة','tasks')}</span></div>{manager&&<label className="chip"><input type="checkbox" checked={all} onChange={(e)=>setAll(e.target.checked)}/> {t('عرض كل الفريق','Show whole team')}</label>}</div><div className="table-wrap"><table className="data-table"><thead><tr><th>Ticket</th><th>Transaction / request</th><th>{t('الإجراء','Requested action')}</th><th>{t('المسند إليه','Assigned to')}</th><th>{t('الموعد النهائي','Deadline')}</th><th>Priority</th><th>Status</th><th /></tr></thead><tbody>{tasks.map((row)=>{const overdue=!!row.due_at&&new Date(row.due_at).getTime()<Date.now()&&!['resolved','closed'].includes(row.ticket_status);return <tr key={row.id} className={overdue?'row-pending':''}><td className="mono">{row.ticket_no||`TKT-${row.id}`}</td><td><strong>{row.subject||'—'}</strong><div className="cell-sub">{row.description||''}</div></td><td>{row.action_requested||'—'}</td><td><select className="filter-select" value={row.assigned_to||''} onChange={(e)=>void update(row.id,{assigned_to:e.target.value||null})}><option value="">Unassigned</option>{operators.map((o)=><option key={o.username} value={o.username}>{o.display_name||o.username}</option>)}</select></td><td className={`mono${overdue?' task-overdue':''}`}>{overdue?'⚠ ':''}{row.due_at?new Date(row.due_at).toLocaleString():'—'}</td><td><span className={`pay-status-badge ${row.priority==='high'?'st-declined':row.priority==='medium'?'st-pending':'st-dim'}`}>{row.priority||'normal'}</span></td><td><select className="filter-select" value={row.ticket_status} onChange={(e)=>void update(row.id,{ticket_status:e.target.value})}><option value="open">Open</option><option value="in_progress">In progress</option><option value="resolved">Resolved</option><option value="closed">Closed</option></select></td><td><button className="btn-ghost btn-sm" onClick={()=>void update(row.id,{action_requested:prompt('Requested action',row.action_requested||'')||row.action_requested})}>{t('تعديل','Edit')}</button></td></tr>})}{tasks.length===0&&<tr><td colSpan={8} className="sidebar-hint">{t('لا توجد مهام مسندة.','No assigned tasks.')}</td></tr>}</tbody></table></div></section>
  </PanelShell>
}
