import { useCallback, useEffect, useMemo, useState } from 'react'
import { Activity, ArrowDownToLine, ArrowUpFromLine, CheckCircle2, Copy, Plus, RefreshCw, Send, Webhook, XCircle } from 'lucide-react'
import PanelShell from '../components/PanelShell'
import { api } from '../lib/api'
import { useLocale } from '../lib/locale'

type Endpoint={id:string;name:string;direction:'inbound'|'outbound';merchant_id:string|null;url:string|null;event_types:string[];is_active:boolean;created_by_name:string|null;created_at:string}
type Log={id:number;endpoint_id:string;direction:string;event_type:string|null;status_code:number|null;success:boolean;latency_ms:number|null;request_id:string|null;error:string|null;created_at:string}
type Data={endpoints:Endpoint[];merchants:{id:string;name:string}[];logs:Log[];kpis:{endpoints:number;active:number;deliveries:number;successRate:number;failed:number}}
const today=()=>new Date().toISOString().slice(0,10)

export default function WebhookCenter(){
 const {t}=useLocale(); const [data,setData]=useState<Data|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [message,setMessage]=useState(''); const [direction,setDirection]=useState(''); const [from,setFrom]=useState(today()); const [to,setTo]=useState(today());
 const [form,setForm]=useState({name:'',direction:'outbound' as 'inbound'|'outbound',url:'',merchant_id:'',events:'payment.approved,payment.declined'}); const [credential,setCredential]=useState<{secret:string;inboundUrl:string|null}|null>(null); const [saving,setSaving]=useState(false)
 const load=useCallback(async()=>{setLoading(true);try{const q=new URLSearchParams({from,to});if(direction)q.set('direction',direction);setData(await api<Data>(`/api/webhooks?${q}`));setError('')}catch(e){setError(e instanceof Error?e.message:t('تعذر تحميل Webhooks.','Could not load webhooks.'))}finally{setLoading(false)}},[direction,from,to,t])
 useEffect(()=>{void load()},[load]); const names=useMemo(()=>new Map((data?.endpoints??[]).map(x=>[x.id,x.name])),[data])
 const create=async()=>{setSaving(true);setError('');try{const res=await api<{signing_secret:string;inbound_url:string|null}>('/api/webhooks',{method:'POST',body:JSON.stringify({...form,event_types:form.events.split(',').map(x=>x.trim()).filter(Boolean)})});setCredential({secret:res.signing_secret,inboundUrl:res.inbound_url});setForm({name:'',direction:'outbound',url:'',merchant_id:'',events:'payment.approved,payment.declined'});await load()}catch(e){setError(e instanceof Error?e.message:'Create failed')}finally{setSaving(false)}}
 const toggle=async(row:Endpoint)=>{await api(`/api/webhooks/${row.id}/toggle`,{method:'POST',body:JSON.stringify({is_active:!row.is_active})});await load()}
 const test=async(row:Endpoint)=>{setMessage('');setError('');try{const r=await api<{status_code:number|null;latency_ms:number}>(`/api/webhooks/${row.id}/test`,{method:'POST'});setMessage(`Delivered · HTTP ${r.status_code} · ${r.latency_ms} ms`);await load()}catch(e){setError(e instanceof Error?e.message:'Test failed');await load()}}
 const copy=(value:string)=>void navigator.clipboard.writeText(value)
 return <PanelShell><section className="page-head webhook-head"><div><span className="guide-eyebrow">DEVELOPER OPERATIONS</span><h2><Webhook size={24}/> {t('مركز Webhooks','Webhook Center')}</h2><p className="page-sub">{t('إنشاء نقاط واردة وصادرة، اختبار التسليم، ومراجعة الأداء من مكان واحد.','Create inbound and outbound endpoints, test delivery, and review performance in one place.')}</p></div><button className="btn-ghost btn-sm" disabled={loading} onClick={()=>void load()}><RefreshCw size={15} className={loading?'spin':''}/>Refresh</button></section>
 {error&&<div className="card warn">{error}</div>}{message&&<div className="card webhook-success">{message}</div>}
 <section className="webhook-kpis"><article><Webhook/><span>Endpoints</span><strong>{data?.kpis.endpoints??0}</strong></article><article><Activity/><span>Active</span><strong>{data?.kpis.active??0}</strong></article><article><CheckCircle2/><span>Success rate</span><strong>{data?.kpis.successRate??0}%</strong></article><article><XCircle/><span>Failed</span><strong>{data?.kpis.failed??0}</strong></article></section>
 <section className="webhook-layout"><div className="card webhook-builder"><div className="recent-head"><div><h3><Plus size={18}/> Generate webhook</h3><span className="cell-sub">Signing secret is shown once.</span></div></div><div className="webhook-form"><label>Name<input className="login-input" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Merchant status callback"/></label><label>Direction<select className="login-input" value={form.direction} onChange={e=>setForm({...form,direction:e.target.value as 'inbound'|'outbound'})}><option value="outbound">Outbound</option><option value="inbound">Inbound</option></select></label>{form.direction==='outbound'&&<label className="span-2">Destination URL<input className="login-input" type="url" value={form.url} onChange={e=>setForm({...form,url:e.target.value})} placeholder="https://merchant.example/webhook"/></label>}<label>Merchant<select className="login-input" value={form.merchant_id} onChange={e=>setForm({...form,merchant_id:e.target.value})}><option value="">Global / unassigned</option>{(data?.merchants??[]).map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label>Events<input className="login-input" value={form.events} onChange={e=>setForm({...form,events:e.target.value})}/></label></div><button className="btn-primary" disabled={saving||!form.name||(form.direction==='outbound'&&!form.url)} onClick={()=>void create()}><Plus size={16}/>{saving?'Creating…':'Create webhook'}</button></div>
 <div className="card webhook-endpoints"><div className="recent-head"><h3>Configured endpoints</h3><span className="cell-sub">{data?.kpis.active??0} active</span></div><div className="webhook-endpoint-list">{(data?.endpoints??[]).map(row=><article key={row.id}><span className={`webhook-direction ${row.direction}`}>{row.direction==='inbound'?<ArrowDownToLine/>:<ArrowUpFromLine/>}</span><div><strong>{row.name}</strong><span className="mono">{row.url??'Generated inbound URL'}</span><small>{row.event_types.join(', ')||'All events'} · by {row.created_by_name??'system'}</small></div><div className="webhook-row-actions"><span className={`pay-status-badge ${row.is_active?'st-paid':'st-dim'}`}>{row.is_active?'Active':'Inactive'}</span>{row.direction==='outbound'&&<button className="btn-ghost btn-sm" disabled={!row.is_active} onClick={()=>void test(row)}><Send size={14}/>Test</button>}<button className="btn-ghost btn-sm" onClick={()=>void toggle(row)}>{row.is_active?'Disable':'Enable'}</button></div></article>)}{!loading&&!data?.endpoints.length&&<p className="sidebar-hint">No webhook endpoints yet.</p>}</div></div></section>
 {credential&&<section className="card webhook-credential"><div><h3>Save these credentials now</h3><p>They will not be shown again.</p></div>{credential.inboundUrl&&<label>Inbound URL<span className="mono">{credential.inboundUrl}</span><button onClick={()=>copy(credential.inboundUrl!)}><Copy size={14}/></button></label>}<label>Signing secret<span className="mono">{credential.secret}</span><button onClick={()=>copy(credential.secret)}><Copy size={14}/></button></label><button className="btn-primary btn-sm" onClick={()=>setCredential(null)}>I saved them</button></section>}
 <section className="card recent-card"><div className="filter-bar webhook-filter"><strong>Delivery report</strong><select className="login-input" value={direction} onChange={e=>setDirection(e.target.value)}><option value="">All directions</option><option value="inbound">Inbound</option><option value="outbound">Outbound</option></select><input className="login-input" type="date" value={from} onChange={e=>setFrom(e.target.value)}/><input className="login-input" type="date" value={to} onChange={e=>setTo(e.target.value)}/></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Result</th><th>Endpoint</th><th>Direction</th><th>Event</th><th>HTTP</th><th>Latency</th><th>Request ID</th><th>Time</th></tr></thead><tbody>{(data?.logs??[]).map(row=><tr key={row.id}><td><span className={`pay-status-badge ${row.success?'st-paid':'st-declined'}`}>{row.success?'Delivered':'Failed'}</span></td><td>{names.get(row.endpoint_id)??'—'}</td><td>{row.direction}</td><td className="mono">{row.event_type??'—'}</td><td className="mono">{row.status_code??'—'}</td><td className="mono">{row.latency_ms??'—'} ms</td><td className="mono">{row.request_id??'—'}</td><td className="mono">{new Date(row.created_at).toLocaleString()}</td></tr>)}{!loading&&!data?.logs.length&&<tr><td colSpan={8}>No deliveries in this scope.</td></tr>}</tbody></table></div></section>
 </PanelShell>
}
