create table if not exists public.internal_chat_rooms (
  id uuid primary key default gen_random_uuid(),
  name text,
  kind text not null default 'group' check (kind in ('direct','group')),
  created_by uuid not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.internal_chat_members (
  room_id uuid not null references public.internal_chat_rooms(id) on delete cascade,
  user_id uuid not null,
  joined_at timestamptz not null default now(),
  last_read_at timestamptz,
  primary key (room_id, user_id)
);

create table if not exists public.internal_chat_messages (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.internal_chat_rooms(id) on delete cascade,
  sender_id uuid not null,
  body text not null check (char_length(body) between 1 and 4000),
  created_at timestamptz not null default now(),
  edited_at timestamptz
);

create table if not exists public.internal_chat_presence (
  user_id uuid primary key,
  last_seen_at timestamptz not null default now()
);

create index if not exists internal_chat_messages_room_created_idx on public.internal_chat_messages(room_id, created_at desc);
create index if not exists internal_chat_members_user_idx on public.internal_chat_members(user_id, room_id);
alter table public.internal_chat_rooms enable row level security;
alter table public.internal_chat_members enable row level security;
alter table public.internal_chat_messages enable row level security;
alter table public.internal_chat_presence enable row level security;

-- Chat is reachable only through the authenticated application server. The
-- browser never receives a service-role credential and anon/authenticated get
-- no direct table grants.
revoke all on public.internal_chat_rooms, public.internal_chat_members, public.internal_chat_messages, public.internal_chat_presence from anon, authenticated;
grant select, insert, update, delete on public.internal_chat_rooms, public.internal_chat_members, public.internal_chat_messages, public.internal_chat_presence to service_role;
grant usage, select on sequence public.internal_chat_messages_id_seq to service_role;
