-- Maven ↔ OnTarget v2 reconciliation foundation.
-- This migration is deliberately provider-neutral: no Maven endpoint is
-- inferred here. The reconcile worker must use the existing, documented
-- client once its endpoint contract is available.

ALTER TABLE public.maven_transactions
  ADD COLUMN IF NOT EXISTS created_at_utc timestamptz,
  ADD COLUMN IF NOT EXISTS modified_at_utc timestamptz,
  ADD COLUMN IF NOT EXISTS paid_source text,
  ADD COLUMN IF NOT EXISTS provider_commission numeric,
  ADD COLUMN IF NOT EXISTS needs_review boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS reconciled_from_provider boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS row_hash text;

DO $$ BEGIN
  ALTER TABLE public.maven_transactions
    ADD CONSTRAINT maven_transactions_paid_source_ck
    CHECK (paid_source IS NULL OR paid_source IN ('provider_auto','operator','manual_edit','reconciliation'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE OR REPLACE FUNCTION public.parse_maven_utc(p_value text)
RETURNS timestamptz
LANGUAGE plpgsql IMMUTABLE SET search_path TO public AS $$
DECLARE v text := nullif(trim(p_value), '');
BEGIN
  IF v IS NULL THEN RETURN NULL; END IF;
  -- Maven exports both ISO values (with Z/offset) and naive UTC text.
  IF v ~* '(z|[+-][0-9]{2}:[0-9]{2})$' THEN
    RETURN v::timestamptz;
  END IF;
  RETURN replace(v, 'T', ' ')::timestamp AT TIME ZONE 'UTC';
EXCEPTION WHEN others THEN
  RETURN NULL;
END $$;

CREATE OR REPLACE FUNCTION public.trg_maven_timestamp_columns()
RETURNS trigger LANGUAGE plpgsql SET search_path TO public AS $$
BEGIN
  NEW.created_at_utc := public.parse_maven_utc(NEW.created_utc);
  NEW.modified_at_utc := public.parse_maven_utc(NEW.modified_utc);
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS trg_maven_timestamp_columns ON public.maven_transactions;
CREATE TRIGGER trg_maven_timestamp_columns
BEFORE INSERT OR UPDATE OF created_utc, modified_utc ON public.maven_transactions
FOR EACH ROW EXECUTE FUNCTION public.trg_maven_timestamp_columns();

UPDATE public.maven_transactions
SET created_at_utc = public.parse_maven_utc(created_utc),
    modified_at_utc = public.parse_maven_utc(modified_utc)
WHERE created_at_utc IS DISTINCT FROM public.parse_maven_utc(created_utc)
   OR modified_at_utc IS DISTINCT FROM public.parse_maven_utc(modified_utc);

CREATE INDEX IF NOT EXISTS ix_mt_merchant_created_at_utc
  ON public.maven_transactions (merchant, created_at_utc);
CREATE INDEX IF NOT EXISTS ix_mt_status_modified_at_utc
  ON public.maven_transactions (status, modified_at_utc);
CREATE UNIQUE INDEX IF NOT EXISTS ux_mt_tx_id ON public.maven_transactions (tx_id);

CREATE TABLE IF NOT EXISTS public.maven_transaction_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tx_id bigint NOT NULL,
  old_status text,
  new_status text NOT NULL,
  source text NOT NULL CHECK (source IN ('provider_auto','operator','manual_edit','reconciliation','collector')),
  actor text,
  provider_modified_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tx_id, old_status, new_status, source, provider_modified_at)
);
CREATE INDEX IF NOT EXISTS ix_maven_tx_history_tx ON public.maven_transaction_history (tx_id, created_at DESC);
ALTER TABLE public.maven_transaction_history ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS maven_transaction_history_service ON public.maven_transaction_history;
CREATE POLICY maven_transaction_history_service ON public.maven_transaction_history
  FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public.maven_reconcile_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  merchant text,
  window_start timestamptz NOT NULL,
  window_end timestamptz NOT NULL,
  rows_provider integer NOT NULL DEFAULT 0,
  rows_local integer NOT NULL DEFAULT 0,
  inserted integer NOT NULL DEFAULT 0,
  updated integer NOT NULL DEFAULT 0,
  alerts integer NOT NULL DEFAULT 0,
  duration_ms integer,
  error text,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_maven_reconcile_runs_created ON public.maven_reconcile_runs (created_at DESC);
ALTER TABLE public.maven_reconcile_runs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS maven_reconcile_runs_service ON public.maven_reconcile_runs;
CREATE POLICY maven_reconcile_runs_service ON public.maven_reconcile_runs
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- Fee booking is intentionally explicit and does not change the configured
-- 3%/4% rates. payin_commission_pct is stored as a percentage (3 => 3%).
CREATE OR REPLACE FUNCTION public.book_deposit_fees(p_tx_id bigint)
RETURNS jsonb LANGUAGE plpgsql SET search_path TO public AS $$
DECLARE t public.maven_transactions; h record; provider numeric; fee numeric; comm numeric;
BEGIN
  SELECT * INTO t FROM public.maven_transactions WHERE tx_id = p_tx_id FOR UPDATE;
  IF NOT FOUND THEN RETURN jsonb_build_object('ok',false,'error','not_found'); END IF;
  SELECT mh.commission_rate, mh.payin_commission_pct INTO h
  FROM public.merchants_hierarchy mh
  WHERE mh.name = t.sub_merchant OR mh.name = t.merchant
  ORDER BY (mh.name = t.sub_merchant) DESC, mh.active DESC, mh.id DESC LIMIT 1;
  fee := COALESCE(t.amount,0) * COALESCE(h.commission_rate,0);
  comm := COALESCE(t.amount,0) * COALESCE(h.payin_commission_pct,0) / 100;
  provider := CASE
    WHEN COALESCE(t.raw, '{}'::jsonb)->>'Commision' ~ '^[-+]?[0-9]+(\\.[0-9]+)?$' THEN (t.raw->>'Commision')::numeric
    WHEN COALESCE(t.raw, '{}'::jsonb)->>'Commission' ~ '^[-+]?[0-9]+(\\.[0-9]+)?$' THEN (t.raw->>'Commission')::numeric
    WHEN COALESCE(t.maven_raw_row, '{}'::jsonb)->>'Commision' ~ '^[-+]?[0-9]+(\\.[0-9]+)?$' THEN (t.maven_raw_row->>'Commision')::numeric
    ELSE NULL END;
  UPDATE public.maven_transactions SET fees = fee, commission = comm, provider_commission = provider WHERE tx_id = p_tx_id;
  RETURN jsonb_build_object('ok',true,'fees',fee,'commission',comm,'provider_commission',provider);
END $$;

CREATE OR REPLACE VIEW public.v_merchant_daily_utc AS
SELECT merchant, (created_at_utc AT TIME ZONE 'UTC')::date AS day_utc,
  count(*) FILTER (WHERE upper(status)='PAID') AS paid_n,
  COALESCE(sum(amount) FILTER (WHERE upper(status)='PAID'),0) AS paid_amt,
  count(*) FILTER (WHERE upper(status)='DECLINED') AS declined_n,
  COALESCE(sum(amount) FILTER (WHERE upper(status)='DECLINED'),0) AS declined_amt,
  count(*) FILTER (WHERE upper(status) NOT IN ('PAID','DECLINED')) AS other_n,
  COALESCE(sum(amount) FILTER (WHERE upper(status) NOT IN ('PAID','DECLINED')),0) AS other_amt,
  COALESCE(sum(fees) FILTER (WHERE upper(status)='PAID'),0) AS fees,
  COALESCE(sum(commission) FILTER (WHERE upper(status)='PAID'),0) AS commission,
  COALESCE(sum(provider_commission) FILTER (WHERE upper(status)='PAID'),0) AS provider_commission
FROM public.maven_transactions GROUP BY merchant, (created_at_utc AT TIME ZONE 'UTC')::date;

CREATE OR REPLACE VIEW public.v_merchant_daily_cairo AS
SELECT merchant, (created_at_utc AT TIME ZONE 'Africa/Cairo')::date AS day_cairo,
  count(*) FILTER (WHERE upper(status)='PAID') AS paid_n,
  COALESCE(sum(amount) FILTER (WHERE upper(status)='PAID'),0) AS paid_amt,
  count(*) FILTER (WHERE upper(status)='DECLINED') AS declined_n,
  COALESCE(sum(amount) FILTER (WHERE upper(status)='DECLINED'),0) AS declined_amt,
  count(*) FILTER (WHERE upper(status) NOT IN ('PAID','DECLINED')) AS other_n,
  COALESCE(sum(amount) FILTER (WHERE upper(status) NOT IN ('PAID','DECLINED')),0) AS other_amt,
  COALESCE(sum(fees) FILTER (WHERE upper(status)='PAID'),0) AS fees,
  COALESCE(sum(commission) FILTER (WHERE upper(status)='PAID'),0) AS commission,
  COALESCE(sum(provider_commission) FILTER (WHERE upper(status)='PAID'),0) AS provider_commission
FROM public.maven_transactions GROUP BY merchant, (created_at_utc AT TIME ZONE 'Africa/Cairo')::date;

CREATE OR REPLACE VIEW public.v_provider_vs_local_mismatch AS
SELECT * FROM public.maven_transactions WHERE needs_review
UNION ALL
SELECT mt.* FROM public.maven_transactions mt
WHERE mt.last_status_change >= now() - interval '7 days' AND mt.reconciled_from_provider = true;
