-- Link withdrawal SMS to the paying wallet and apply each balance change once.
-- receiver_number is deliberately excluded: on withdrawals it is the beneficiary.

create table if not exists public.wallet_balance_movements (
  id bigint generated by default as identity primary key,
  sms_id bigint not null unique references public.inbound_sms(id) on delete restrict,
  wallet_number text not null,
  movement_type text not null check (movement_type in ('withdrawal')),
  amount numeric(18,2) not null check (amount >= 0),
  balance_before numeric(18,2),
  balance_after numeric(18,2),
  balance_source text not null check (balance_source in ('sms_balance_after','calculated','unresolved')),
  occurred_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.wallet_balance_movements enable row level security;
revoke all on table public.wallet_balance_movements from anon, authenticated;

create or replace function public.apply_withdrawal_sms_to_wallet_balance()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_wallet text;
  v_key text;
  v_before numeric(18,2);
  v_after numeric(18,2);
  v_source text;
  v_inserted bigint;
begin
  if new.sms_category is distinct from 'withdrawal' or coalesce(new.amount, 0) <= 0 then
    return new;
  end if;

  v_wallet := coalesce(
    nullif(btrim(new.confirmed_wallet_number), ''),
    nullif(btrim(new.manual_wallet_from), ''),
    nullif(btrim(new.wallet_number), ''),
    nullif(btrim(new.wallet), '')
  );
  if v_wallet is null then return new; end if;
  v_key := right(regexp_replace(v_wallet, '\D', '', 'g'), 11);
  if v_key = '' then return new; end if;

  select pa.current_balance into v_before
  from public.payment_accounts pa
  where right(regexp_replace(pa.account_number, '\D', '', 'g'), 11) = v_key
  order by pa.is_active desc nulls last, pa.created_at desc
  limit 1;

  if v_before is null then
    select ds.balance into v_before
    from public.wallet_device_map wm
    join public.device_status ds
      on ds.device = wm.device
     and (wm.sim_slot is null or ds.sim_slot = wm.sim_slot)
    where right(regexp_replace(wm.to_account_number, '\D', '', 'g'), 11) = v_key
    order by ds.last_seen_at desc nulls last
    limit 1;
  end if;

  if new.balance_after is not null then
    v_after := new.balance_after;
    v_source := 'sms_balance_after';
  elsif v_before is not null then
    v_after := greatest(0, v_before - new.amount);
    v_source := 'calculated';
  else
    v_after := null;
    v_source := 'unresolved';
  end if;

  insert into public.wallet_balance_movements
    (sms_id, wallet_number, movement_type, amount, balance_before, balance_after, balance_source, occurred_at)
  values
    (new.id, v_wallet, 'withdrawal', new.amount, v_before, v_after, v_source, new.received_at)
  on conflict (sms_id) do nothing
  returning id into v_inserted;

  -- A replay/upsert of the same SMS never changes the balance twice.
  if v_inserted is null or v_after is null then return new; end if;

  update public.payment_accounts
  set current_balance = v_after, balance_updated_at = coalesce(new.received_at, now())
  where right(regexp_replace(account_number, '\D', '', 'g'), 11) = v_key;

  update public.device_status ds
  set balance = v_after, balance_at = coalesce(new.received_at, now())
  from public.wallet_device_map wm
  where right(regexp_replace(wm.to_account_number, '\D', '', 'g'), 11) = v_key
    and ds.device = wm.device
    and (wm.sim_slot is null or ds.sim_slot = wm.sim_slot);

  return new;
end;
$$;

revoke execute on function public.apply_withdrawal_sms_to_wallet_balance() from public, anon, authenticated;

drop trigger if exists trg_apply_withdrawal_sms_wallet_balance on public.inbound_sms;
drop trigger if exists trg_apply_withdrawal_sms_wallet_balance_insert on public.inbound_sms;
drop trigger if exists trg_apply_withdrawal_sms_wallet_balance_update on public.inbound_sms;
create trigger trg_apply_withdrawal_sms_wallet_balance_insert
after insert on public.inbound_sms
for each row execute function public.apply_withdrawal_sms_to_wallet_balance();
create trigger trg_apply_withdrawal_sms_wallet_balance_update
after update of sms_category, amount, wallet_number, confirmed_wallet_number, manual_wallet_from, balance_after
on public.inbound_sms
for each row
when (
  old.sms_category is distinct from new.sms_category
  or old.amount is distinct from new.amount
  or old.wallet_number is distinct from new.wallet_number
  or old.confirmed_wallet_number is distinct from new.confirmed_wallet_number
  or old.manual_wallet_from is distinct from new.manual_wallet_from
  or old.balance_after is distinct from new.balance_after
)
execute function public.apply_withdrawal_sms_to_wallet_balance();

create index if not exists wallet_balance_movements_wallet_occurred_idx
  on public.wallet_balance_movements (wallet_number, occurred_at desc);
