create table if not exists public.sms_withdrawal_assignments (
  id bigint generated by default as identity primary key,
  sms_id bigint not null unique references public.inbound_sms(id) on delete cascade,
  assignment_type text not null check (assignment_type in ('payout', 'p2p_usdt', 'cash_return')),
  target_reference text,
  display_name text not null check (length(trim(display_name)) > 0),
  note text,
  assigned_by text not null,
  assigned_by_id text,
  assigned_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists sms_withdrawal_assignments_type_time_idx
  on public.sms_withdrawal_assignments (assignment_type, assigned_at desc);

alter table public.sms_withdrawal_assignments enable row level security;
revoke all on public.sms_withdrawal_assignments from anon, authenticated;
grant all on public.sms_withdrawal_assignments to service_role;
